/*!
 * Copyright Unlok, Vaughn Royko 2011-2019
 * http://www.unlok.ca
 *
 * Credits & Thanks:
 * http://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://waywardgame.github.io/
 */
/**
 * Note: If you rename a Bindable and don't make a save conversion for it, the old binding will be lost.
 * Note: All Bindables should start with a BindableType name.
 */
declare enum Bindable {
    /**
     * Safe for `if` statements. Falsey!
     */
    None = 0,
    GameMoveDirection = 1,
    GameMoveDown = 2,
    GameMoveLeft = 3,
    GameMoveRight = 4,
    GameMoveUp = 5,
    GameMoveToTile = 6,
    GameMoveToTilePreview = 7,
    GameMoveToTileCancel = 8,
    GameFaceDirection = 9,
    GameFaceDown = 10,
    GameFaceLeft = 11,
    GameFaceRight = 12,
    GameFaceUp = 13,
    GameIdle = 14,
    GameActions = 15,
    GameItemMove = 16,
    GameItemMoveAll = 17,
    GameItemMenu = 18,
    GameItemQuickMove = 19,
    GameItemQuickMoveAll = 20,
    GameItemDrop = 21,
    GameItemDropAll = 22,
    GameItemEquipToggle = 23,
    GameHandToggleLeft = 24,
    GameHandToggleRight = 25,
    GameInspect = 26,
    GameMoreInformation = 27,
    GameZoomIn = 28,
    GameZoomOut = 29,
    GamePause = 30,
    GameSave = 31,
    GameFullscreen = 32,
    GameScreenshotMode = 33,
    GameQuickSlotClear = 34,
    GameQuickSlot1 = 35,
    GameQuickSlot2 = 36,
    GameQuickSlot3 = 37,
    GameQuickSlot4 = 38,
    GameQuickSlot5 = 39,
    GameQuickSlot6 = 40,
    GameQuickSlot7 = 41,
    GameQuickSlot8 = 42,
    GameQuickSlot9 = 43,
    GameQuickSlotToggle1 = 44,
    GameQuickSlotToggle2 = 45,
    GameQuickSlotToggle3 = 46,
    GameQuickSlotToggle4 = 47,
    GameQuickSlotToggle5 = 48,
    GameQuickSlotToggle6 = 49,
    GameQuickSlotToggle7 = 50,
    GameQuickSlotToggle8 = 51,
    GameQuickSlotToggle9 = 52,
    GameContextMenu1 = 53,
    GameContextMenu2 = 54,
    GameContextMenu3 = 55,
    GameContextMenu4 = 56,
    GameContextMenu5 = 57,
    GameContextMenu6 = 58,
    GameContextMenu7 = 59,
    GameContextMenu8 = 60,
    GameContextMenu9 = 61,
    GameContextMenu10 = 62,
    GameContextMenu11 = 63,
    GameContextMenu12 = 64,
    GameContextMenu13 = 65,
    GameContextMenu14 = 66,
    GameContextMenu15 = 67,
    GameContextMenu16 = 68,
    GameContextMenu17 = 69,
    GameContextMenu18 = 70,
    GameContextMenu19 = 71,
    GameContextMenu20 = 72,
    GameContextMenu21 = 73,
    GameContextMenu22 = 74,
    GameContextMenu23 = 75,
    GameContextMenu24 = 76,
    DialogCloseAll = 77,
    DialogOptions = 78,
    DialogHelp = 79,
    DialogMilestones = 80,
    DialogNotes = 81,
    DialogMessages = 82,
    DialogMessagesChatFocus = 83,
    DialogInventory = 84,
    DialogCrafting = 85,
    DialogDismantle = 86,
    DialogEquipment = 87,
    DialogSkills = 88,
    DialogQuests = 89,
    MenuEnter = 90,
    MenuNext = 91,
    MenuPrevious = 92,
    MenuUp = 93,
    MenuDown = 94,
    MenuLeft = 95,
    MenuRight = 96,
    MenuCancel = 97,
    MenuContextMenu = 98,
    DeveloperToggleDeveloperMode = 99,
    DeveloperToggleDeveloperTools = 100,
    DeveloperReloadGame = 101,
    DeveloperReloadAndContinueGame = 102
}
export default Bindable;
export declare enum BindableType {
    Game = 0,
    Dialog = 1,
    Menu = 2,
    Developer = 3,
    Mod = 4
}
