/*!
 * Copyright Unlok, Vaughn Royko 2011-2020
 * http://www.unlok.ca
 *
 * Credits & Thanks:
 * http://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
/**
 * Note: If you rename a Bindable and don't make a save conversion for it, the old binding will be lost.
 * Note: All Bindables should start with a BindableType name.
 */
declare enum Bindable {
    /**
     * Safe for `if` statements. Falsey!
     */
    None = 0,
    GameMoveDirection = 1,
    GameMoveDown = 2,
    GameMoveLeft = 3,
    GameMoveRight = 4,
    GameMoveUp = 5,
    GameMoveToTile = 6,
    GameMoveToTilePreview = 7,
    GameMoveToTileCancel = 8,
    GameFaceDirection = 9,
    GameFaceDown = 10,
    GameFaceLeft = 11,
    GameFaceRight = 12,
    GameFaceUp = 13,
    GameIdle = 14,
    GameActions = 15,
    GameItemMove = 16,
    GameItemMoveAll = 17,
    GameItemMenu = 18,
    GameItemQuickMove = 19,
    GameItemQuickMoveAll = 20,
    GameItemDrop = 21,
    GameItemDropAll = 22,
    GameItemEquipToggle = 23,
    GameItemProtectToggle = 24,
    GameHandToggleLeft = 25,
    GameHandToggleRight = 26,
    GameInspect = 27,
    GameMoreInformation = 28,
    GameZoomIn = 29,
    GameZoomOut = 30,
    GamePause = 31,
    GameSave = 32,
    GameFullscreen = 33,
    GameScreenshotMode = 34,
    GameQuickSlotClear = 35,
    GameQuickSlot1 = 36,
    GameQuickSlot2 = 37,
    GameQuickSlot3 = 38,
    GameQuickSlot4 = 39,
    GameQuickSlot5 = 40,
    GameQuickSlot6 = 41,
    GameQuickSlot7 = 42,
    GameQuickSlot8 = 43,
    GameQuickSlot9 = 44,
    GameQuickSlotToggle1 = 45,
    GameQuickSlotToggle2 = 46,
    GameQuickSlotToggle3 = 47,
    GameQuickSlotToggle4 = 48,
    GameQuickSlotToggle5 = 49,
    GameQuickSlotToggle6 = 50,
    GameQuickSlotToggle7 = 51,
    GameQuickSlotToggle8 = 52,
    GameQuickSlotToggle9 = 53,
    GameContextMenu1 = 54,
    GameContextMenu2 = 55,
    GameContextMenu3 = 56,
    GameContextMenu4 = 57,
    GameContextMenu5 = 58,
    GameContextMenu6 = 59,
    GameContextMenu7 = 60,
    GameContextMenu8 = 61,
    GameContextMenu9 = 62,
    GameContextMenu10 = 63,
    GameContextMenu11 = 64,
    GameContextMenu12 = 65,
    GameContextMenu13 = 66,
    GameContextMenu14 = 67,
    GameContextMenu15 = 68,
    GameContextMenu16 = 69,
    GameContextMenu17 = 70,
    GameContextMenu18 = 71,
    GameContextMenu19 = 72,
    GameContextMenu20 = 73,
    GameContextMenu21 = 74,
    GameContextMenu22 = 75,
    GameContextMenu23 = 76,
    GameContextMenu24 = 77,
    DialogCloseAll = 78,
    DialogOptions = 79,
    DialogHelp = 80,
    DialogMilestones = 81,
    DialogNotes = 82,
    DialogMessages = 83,
    DialogMessagesChatFocus = 84,
    DialogInventory = 85,
    DialogCrafting = 86,
    DialogDismantle = 87,
    DialogEquipment = 88,
    DialogSkills = 89,
    DialogQuests = 90,
    MenuEnter = 91,
    MenuNext = 92,
    MenuPrevious = 93,
    MenuUp = 94,
    MenuDown = 95,
    MenuLeft = 96,
    MenuRight = 97,
    MenuCancel = 98,
    MenuContextMenu = 99,
    MenuSelect = 100,
    DeveloperToggleDeveloperMode = 101,
    DeveloperToggleDeveloperTools = 102,
    DeveloperReloadGame = 103,
    DeveloperReloadAndContinueGame = 104,
    DeveloperReloadStylesheets = 105
}
export default Bindable;
export declare enum BindableType {
    Game = 0,
    Dialog = 1,
    Menu = 2,
    Developer = 3,
    Mod = 4
}
