/*!
 * Copyright 2011-2023 Unlok
 * https://www.unlok.ca
 *
 * Credits & Thanks:
 * https://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
/**
 * Note: If you rename a Bindable and don't make a save conversion for it, the old binding will be lost.
 * Note: All Bindables should start with a BindableType name.
 */
declare enum Bindable {
    /**
     * Safe for `if` statements. Falsey!
     */
    None = 0,
    GameMoveDirection = 1,
    GameMoveUp = 2,
    GameMoveLeft = 3,
    GameMoveDown = 4,
    GameMoveRight = 5,
    GameMoveToTile = 6,
    GameMoveToTilePreview = 7,
    GameMoveToTileCancel = 8,
    GameFaceDirection = 9,
    GameFaceUp = 10,
    GameFaceLeft = 11,
    GameFaceDown = 12,
    GameFaceRight = 13,
    GameIdle = 14,
    GameItemMove = 15,
    GameItemMoveAll = 16,
    GameItemMoveAllByQuality = 17,
    GameItemMoveToActionSlotAutoUse = 18,
    GameItemMenu = 19,
    GameItemQuickMove = 20,
    GameItemQuickMoveAll = 21,
    GameItemQuickMoveAllByQuality = 22,
    GameItemDrop = 23,
    GameItemDropAll = 24,
    GameItemDropAllByQuality = 25,
    GameItemEquipToggle = 26,
    GameItemProtectToggle = 27,
    GameItemOpen = 28,
    GameItemToggleStacked = 29,
    GameItemToggleStackOpen = 30,
    GameInspect = 31,
    GameInspectItem = 32,
    GameZoomIn = 33,
    GameZoomOut = 34,
    GamePause = 35,
    GameSave = 36,
    GameFullscreen = 37,
    GameScreenshotMode = 38,
    GameActionBarConfigure = 39,
    GameActionBarUseSlottedItem = 40,
    GameActionBarCopy = 41,
    GameActionBarToggleUseWhenMoving = 42,
    GameActionBarClear = 43,
    GameActions = 44,
    GameActionsItems = 45,
    GameActionEquip = 46,
    GameActionEquipLeft = 47,
    GameActionEquipRight = 48,
    GameActionUnequip = 49,
    GameActionCloseContainer = 50,
    GameActionOpenContainer = 51,
    GameActionButcher = 52,
    GameActionHarvest = 53,
    GameActionChop = 54,
    GameActionMine = 55,
    GameActionMelee = 56,
    GameActionGatherLiquid = 57,
    GameActionAttachContainer = 58,
    GameActionDetachContainer = 59,
    GameActionSwapWithArmorStand = 60,
    GameActionEquipFromArmorStand = 61,
    GameActionTakeFromArmorStand = 62,
    GameActionRotate = 63,
    GameActionDumpItems = 64,
    GameActionDisplayItem = 65,
    GameActionDisplayLeft = 66,
    GameActionDisplayRight = 67,
    GameActionKneel = 68,
    GameActionPour = 69,
    GameActionPourOnYourself = 70,
    GameActionDrink = 71,
    GameActionBuild = 72,
    GameActionCraft = 73,
    GameActionDisassemble = 74,
    GameActionDismantle = 75,
    GameActionOffer = 76,
    GameActionRepair = 77,
    GameActionThrow = 78,
    GameActionRename = 79,
    GameActionStartFire = 80,
    GameActionExtinguish = 81,
    GameActionDrop = 82,
    GameActionDropAll = 83,
    GameActionDropAllOfSameQuality = 84,
    GameActionDig = 85,
    GameActionTill = 86,
    GameActionPackGround = 87,
    GameActionEat = 88,
    GameActionCast = 89,
    GameActionRest = 90,
    GameActionSleep = 91,
    GameActionCure = 92,
    GameActionLockpick = 93,
    GameActionUseVehicle = 94,
    GameActionDismount = 95,
    GameActionGrasp = 96,
    GameActionAbsorb = 97,
    GameActionExude = 98,
    GameActionIgnite = 99,
    GameActionSetDown = 100,
    GameActionRubClockwise = 101,
    GameActionRubCounterclockwise = 102,
    GameActionRead = 103,
    GameActionLearn = 104,
    GameActionOpenBottle = 105,
    GameActionSqueeze = 106,
    GameActionGatherWithHands = 107,
    GameActionHarvestWithHands = 108,
    GameActionDigWithHands = 109,
    GameActionTillWithHands = 110,
    GameActionPickUpExcrementWithHands = 111,
    GameActionCageCreature = 112,
    GameActionPickUpItem = 113,
    GameActionPickUpAllItems = 114,
    GameActionPickUpDoodad = 115,
    GameActionTame = 116,
    GameActionRelease = 117,
    GameActionUncage = 118,
    GameActionPet = 119,
    GameActionHitch = 120,
    GameActionUnhitch = 121,
    GameActionToggleHitch = 122,
    GameActionCommandCreature = 123,
    GameActionCreatureFollowCloseAi = 124,
    GameActionCreatureFollowFarAi = 125,
    GameActionCreatureStayAi = 126,
    GameActionCreatureDefendAi = 127,
    GameActionCreatureAttackAi = 128,
    GameActionJump = 129,
    GameActionAttack = 130,
    GameActionPlant = 131,
    GameActionPlaceDown = 132,
    GameActionTrade = 133,
    GameActionShipToIsland = 134,
    GameActionShoot = 135,
    GameActionFire = 136,
    GameActionProtect = 137,
    GameActionUnprotect = 138,
    GameActionSmotherFire = 139,
    GameActionStokeFire = 140,
    GameActionHeal = 141,
    GameActionHealOther = 142,
    GameActionTestDepth = 143,
    GameActionReadMap = 144,
    GameActionPreserve = 145,
    GameActionReinforce = 146,
    GameActionTellTime = 147,
    GameActionEnchant = 148,
    GameActionSailToCivilization = 149,
    GameActionTeleport = 150,
    GameActionDrawMap = 151,
    GameActionApply = 152,
    GameActionRefine = 153,
    GameActionTransmogrify = 154,
    GameActionNavigate = 155,
    GameActionUpgrade = 156,
    GameActionEnhance = 157,
    GameActionAlter = 158,
    GameActionSummon = 159,
    GameActionInvoke = 160,
    GameActionExudeWithItem = 161,
    GameActionAbsorbWithItem = 162,
    GameActionIgniteWithItem = 163,
    GameActionAddFuelWithItem = 164,
    GameActionPreserveWithItem = 165,
    GameActionRefineWithItem = 166,
    GameActionAlterWithItem = 167,
    GameActionUpgradeWithItem = 168,
    GameActionTransmogrifyWithItem = 169,
    GameActionEnchantWithItem = 170,
    GameActionEnhanceWithItem = 171,
    GameActionReinforceWithItem = 172,
    GameActionRepairWithItem = 173,
    GameActionItemMove = 174,
    GameActionItemMoveAll = 175,
    GameActionItemMoveAllOfSameQuality = 176,
    GameActionItemMoveToInventory = 177,
    GameActionTradeBuyFromTrader = 178,
    GameActionTradeSellToTrader = 179,
    GameActionItemMoveToActiveContainer = 180,
    GameActionItemMoveToFacingContainer = 181,
    GameActionMoveContents = 182,
    GameActionOpenDoor = 183,
    GameActionCloseDoor = 184,
    DialogCloseAll = 185,
    DialogOptions = 186,
    DialogHelp = 187,
    DialogMilestones = 188,
    DialogNotes = 189,
    DialogMessages = 190,
    DialogMessagesChatFocus = 191,
    DialogInventory = 192,
    DialogCrafting = 193,
    DialogDismantle = 194,
    DialogEquipment = 195,
    DialogSkills = 196,
    DialogQuests = 197,
    DialogIslands = 198,
    MenuEnter = 199,
    MenuSubmit = 200,
    MenuNext = 201,
    MenuPrevious = 202,
    MenuUp = 203,
    MenuDown = 204,
    MenuLeft = 205,
    MenuRight = 206,
    MenuCancel = 207,
    MenuNextOption = 208,
    MenuMoreInformation = 209,
    MenuPreviousOption = 210,
    MenuContextMenu = 211,
    MenuSelect = 212,
    DeveloperToggleDeveloperMode = 213,
    DeveloperToggleDeveloperTools = 214,
    DeveloperReloadGame = 215,
    DeveloperReloadAndContinueGame = 216,
    DeveloperReloadStylesheets = 217,
    DeveloperReloadTextures = 218,
    GameActionReshape = 219,
    GameActionReshapeWithItem = 220,
    GameActionCreatureHeelAi = 221,
    GameActionOpenTileContainer = 222,
    GameActionCommandCreatureAll = 223
}
export default Bindable;
export declare enum BindableType {
    Game = 0,
    GameItem = 1,
    GameAction = 2,
    GameActionBar = 3,
    Dialog = 4,
    Menu = 5,
    Developer = 6,
    Mod = 7
}
export declare enum BindableTypeContext {
    Default = 0,
    ActionMenu = 1,
    Mod = 2
}
export declare const BINDABLE_TYPE_CONTEXTS: Record<BindableType, BindableTypeContext>;
export declare enum BindableMouseTargetingContext {
    Generic = 0,
    World = 1,
    Item = 2
}
export declare const MOUSE_TARGETING_BINDABLE_CONTEXTS: Record<BindableMouseTargetingContext, Bindable[]>;
