/*!
 * Copyright 2011-2024 Unlok
 * https://www.unlok.ca
 *
 * Credits & Thanks:
 * https://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
/**
 * Note: If you rename a Bindable and don't make a save conversion for it, the old binding will be lost.
 * Note: All Bindables should start with a BindableType name.
 */
declare enum Bindable {
    /**
     * Safe for `if` statements. Falsey!
     */
    None = 0,
    GameMoveDirection = 1,
    GameMoveUp = 2,
    GameMoveLeft = 3,
    GameMoveDown = 4,
    GameMoveRight = 5,
    GameMoveToTile = 6,
    GameMoveToTilePreview = 7,
    GameMoveToTileCancel = 8,
    GameFaceDirection = 9,
    GameFaceUp = 10,
    GameFaceLeft = 11,
    GameFaceDown = 12,
    GameFaceRight = 13,
    GameIdle = 14,
    GameItemMove = 15,
    GameItemMoveAll = 16,
    GameItemMoveAllByQuality = 17,
    GameItemMoveToActionSlotAutoUse = 18,
    GameItemMenu = 19,
    GameItemQuickMove = 20,
    GameItemQuickMoveAll = 21,
    GameItemQuickMoveAllByQuality = 22,
    GameItemDrop = 23,
    GameItemDropAll = 24,
    GameItemDropAllByQuality = 25,
    GameItemEquipToggle = 26,
    GameItemProtectToggle = 27,
    GameItemOpen = 28,
    GameItemToggleStacked = 29,
    GameItemToggleStackOpen = 30,
    GameInspect = 31,
    GameInspectItem = 32,
    GameZoomIn = 33,
    GameZoomOut = 34,
    GamePause = 35,
    GameSave = 36,
    GameFullscreen = 37,
    GameScreenshotMode = 38,
    GameActionBarConfigure = 39,
    GameActionBarUseSlottedItem = 40,
    GameActionBarCopy = 41,
    GameActionBarToggleUseWhenMoving = 42,
    GameActionBarToggleAllUseWhenMoving = 43,
    GameActionBarClear = 44,
    GameActionBarToggleUseHistory = 45,
    GameActions = 46,
    GameActionsItems = 47,
    GameActionsInFront = 48,
    GameActionsItemsInFront = 49,
    GameActionEquip = 50,
    GameActionEquipLeft = 51,
    GameActionEquipRight = 52,
    GameActionUnequip = 53,
    GameActionCloseContainer = 54,
    GameActionOpenContainer = 55,
    GameActionButcher = 56,
    GameActionHarvest = 57,
    GameActionChop = 58,
    GameActionMine = 59,
    GameActionMelee = 60,
    GameActionGatherLiquid = 61,
    GameActionAttachContainer = 62,
    GameActionDetachContainer = 63,
    GameActionSwapWithArmorStand = 64,
    GameActionEquipFromArmorStand = 65,
    GameActionTakeFromArmorStand = 66,
    GameActionRotate = 67,
    GameActionDumpItems = 68,
    GameActionDisplayItem = 69,
    GameActionDisplayLeft = 70,
    GameActionDisplayRight = 71,
    GameActionKneel = 72,
    GameActionPour = 73,
    GameActionPourOnYourself = 74,
    GameActionDrink = 75,
    GameActionBuild = 76,
    GameActionCraft = 77,
    GameActionDisassemble = 78,
    GameActionDismantle = 79,
    GameActionOffer = 80,
    GameActionRepair = 81,
    GameActionThrow = 82,
    GameActionRename = 83,
    GameActionStartFire = 84,
    GameActionExtinguish = 85,
    GameActionDrop = 86,
    GameActionDropAll = 87,
    GameActionDropAllOfSameQuality = 88,
    GameActionDig = 89,
    GameActionTill = 90,
    GameActionPackGround = 91,
    GameActionEat = 92,
    GameActionCast = 93,
    GameActionRest = 94,
    GameActionSleep = 95,
    GameActionCure = 96,
    GameActionLockpick = 97,
    GameActionUseVehicle = 98,
    GameActionDismount = 99,
    GameActionGrasp = 100,
    GameActionAbsorb = 101,
    GameActionExude = 102,
    GameActionIgnite = 103,
    GameActionSetDown = 104,
    GameActionRubClockwise = 105,
    GameActionRubCounterclockwise = 106,
    GameActionRead = 107,
    GameActionLearn = 108,
    GameActionOpenBottle = 109,
    GameActionSqueeze = 110,
    GameActionGatherWithHands = 111,
    GameActionHarvestWithHands = 112,
    GameActionDigWithHands = 113,
    GameActionTillWithHands = 114,
    GameActionPickUpExcrementWithHands = 115,
    GameActionCageCreature = 116,
    GameActionPickUpItem = 117,
    GameActionPickUpAllItems = 118,
    GameActionPickUpDoodad = 119,
    GameActionTame = 120,
    GameActionRelease = 121,
    GameActionUncage = 122,
    GameActionPet = 123,
    GameActionHitch = 124,
    GameActionUnhitch = 125,
    GameActionToggleHitch = 126,
    GameActionCommandCreature = 127,
    GameActionCreatureFollowCloseAi = 128,
    GameActionCreatureFollowFarAi = 129,
    GameActionCreatureStayAi = 130,
    GameActionCreatureDefendAi = 131,
    GameActionCreatureAttackAi = 132,
    GameActionJump = 133,
    GameActionAttack = 134,
    GameActionPlant = 135,
    GameActionPlaceDown = 136,
    GameActionTrade = 137,
    GameActionShipToIsland = 138,
    GameActionShoot = 139,
    GameActionFire = 140,
    GameActionProtect = 141,
    GameActionUnprotect = 142,
    GameActionSmotherFire = 143,
    GameActionStokeFire = 144,
    GameActionHeal = 145,
    GameActionHealOther = 146,
    GameActionTestDepth = 147,
    GameActionReadMap = 148,
    GameActionPreserve = 149,
    GameActionReinforce = 150,
    GameActionTellTime = 151,
    GameActionEnchant = 152,
    GameActionSailToCivilization = 153,
    GameActionTeleport = 154,
    GameActionDrawMap = 155,
    GameActionApply = 156,
    GameActionRefine = 157,
    GameActionTransmogrify = 158,
    GameActionNavigate = 159,
    GameActionUpgrade = 160,
    GameActionEnhance = 161,
    GameActionAlter = 162,
    GameActionSummon = 163,
    GameActionInvoke = 164,
    GameActionExudeWithItem = 165,
    GameActionAbsorbWithItem = 166,
    GameActionIgniteWithItem = 167,
    GameActionAddFuelWithItem = 168,
    GameActionPreserveWithItem = 169,
    GameActionRefineWithItem = 170,
    GameActionAlterWithItem = 171,
    GameActionUpgradeWithItem = 172,
    GameActionTransmogrifyWithItem = 173,
    GameActionEnchantWithItem = 174,
    GameActionEnhanceWithItem = 175,
    GameActionReinforceWithItem = 176,
    GameActionRepairWithItem = 177,
    GameActionItemMove = 178,
    GameActionItemMoveAll = 179,
    GameActionItemMoveAllOfSameQuality = 180,
    GameActionItemMoveToInventory = 181,
    GameActionTradeBuyFromTrader = 182,
    GameActionTradeSellToTrader = 183,
    GameActionItemMoveToActiveContainer = 184,
    GameActionItemMoveToFacingContainer = 185,
    GameActionMoveContents = 186,
    GameActionOpenDoor = 187,
    GameActionCloseDoor = 188,
    DialogCloseAll = 189,
    DialogOptions = 190,
    DialogHelp = 191,
    DialogMilestones = 192,
    DialogNotes = 193,
    DialogMessages = 194,
    DialogMessagesChatFocus = 195,
    DialogInventory = 196,
    DialogCrafting = 197,
    DialogDismantle = 198,
    DialogEquipment = 199,
    DialogSkills = 200,
    DialogQuests = 201,
    DialogIslands = 202,
    HudToggleMenuBar = 203,
    HudToggleActionBar = 204,
    HudToggleMessages = 205,
    HudToggleStats = 206,
    MenuEnter = 207,
    MenuSubmit = 208,
    MenuNext = 209,
    MenuPrevious = 210,
    MenuUp = 211,
    MenuDown = 212,
    MenuLeft = 213,
    MenuRight = 214,
    MenuCancel = 215,
    MenuNextOption = 216,
    MenuMoreInformation = 217,
    MenuPreviousOption = 218,
    MenuContextMenu = 219,
    MenuSelect = 220,
    DeveloperInterfaceScaleUp = 221,
    DeveloperInterfaceScaleDown = 222,
    DeveloperToggleDeveloperMode = 223,
    DeveloperToggleDeveloperTools = 224,
    DeveloperReloadGame = 225,
    DeveloperReloadAndContinueGame = 226,
    DeveloperReloadStylesheets = 227,
    DeveloperReloadTextures = 228,
    GameActionReshape = 229,
    GameActionReshapeWithItem = 230,
    GameActionCreatureHeelAi = 231,
    GameActionOpenTileContainer = 232,
    GameActionCommandCreatureAll = 233
}
export default Bindable;
export declare enum BindableType {
    Game = 0,
    GameItem = 1,
    GameAction = 2,
    GameActionBar = 3,
    Dialog = 4,
    Hud = 5,
    Menu = 6,
    Developer = 7,
    Mod = 8
}
export declare enum BindableTypeContext {
    Default = 0,
    ActionMenu = 1,
    Mod = 2
}
export declare const BINDABLE_TYPE_CONTEXTS: Record<BindableType, BindableTypeContext>;
export declare enum BindableMouseTargetingContext {
    Generic = 0,
    World = 1,
    Item = 2
}
export declare const MOUSE_TARGETING_BINDABLE_CONTEXTS: Record<BindableMouseTargetingContext, Bindable[]>;
