/*!
 * Copyright 2011-2021 Unlok
 * https://www.unlok.ca
 *
 * Credits & Thanks:
 * https://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
/**
 * Note: If you rename a Bindable and don't make a save conversion for it, the old binding will be lost.
 * Note: All Bindables should start with a BindableType name.
 */
declare enum Bindable {
    /**
     * Safe for `if` statements. Falsey!
     */
    None = 0,
    GameMoveDirection = 1,
    GameMoveDown = 2,
    GameMoveLeft = 3,
    GameMoveRight = 4,
    GameMoveUp = 5,
    GameMoveToTile = 6,
    GameMoveToTilePreview = 7,
    GameMoveToTileCancel = 8,
    GameFaceDirection = 9,
    GameFaceDown = 10,
    GameFaceLeft = 11,
    GameFaceRight = 12,
    GameFaceUp = 13,
    GameIdle = 14,
    GameActions = 15,
    GameActionsItems = 16,
    GameItemMove = 17,
    GameItemMoveAll = 18,
    GameItemMenu = 19,
    GameItemQuickMove = 20,
    GameItemQuickMoveAll = 21,
    GameItemDrop = 22,
    GameItemDropAll = 23,
    GameItemEquipToggle = 24,
    GameItemProtectToggle = 25,
    GameHandToggleLeft = 26,
    GameHandToggleRight = 27,
    GameInspect = 28,
    GameInspectItem = 29,
    GameMoreInformation = 30,
    GameZoomIn = 31,
    GameZoomOut = 32,
    GamePause = 33,
    GameSave = 34,
    GameFullscreen = 35,
    GameScreenshotMode = 36,
    GameQuickSlotClear = 37,
    GameQuickSlotBindAction = 38,
    GameQuickSlotBindItemAction = 39,
    GameQuickSlot1 = 40,
    GameQuickSlot2 = 41,
    GameQuickSlot3 = 42,
    GameQuickSlot4 = 43,
    GameQuickSlot5 = 44,
    GameQuickSlot6 = 45,
    GameQuickSlot7 = 46,
    GameQuickSlot8 = 47,
    GameQuickSlot9 = 48,
    GameQuickSlot10 = 49,
    GameQuickSlot11 = 50,
    GameQuickSlot12 = 51,
    GameQuickSlotToggle1 = 52,
    GameQuickSlotToggle2 = 53,
    GameQuickSlotToggle3 = 54,
    GameQuickSlotToggle4 = 55,
    GameQuickSlotToggle5 = 56,
    GameQuickSlotToggle6 = 57,
    GameQuickSlotToggle7 = 58,
    GameQuickSlotToggle8 = 59,
    GameQuickSlotToggle9 = 60,
    GameQuickSlotToggle10 = 61,
    GameQuickSlotToggle11 = 62,
    GameQuickSlotToggle12 = 63,
    GameContextMenu1 = 64,
    GameContextMenu2 = 65,
    GameContextMenu3 = 66,
    GameContextMenu4 = 67,
    GameContextMenu5 = 68,
    GameContextMenu6 = 69,
    GameContextMenu7 = 70,
    GameContextMenu8 = 71,
    GameContextMenu9 = 72,
    GameContextMenu10 = 73,
    GameContextMenu11 = 74,
    GameContextMenu12 = 75,
    GameContextMenu13 = 76,
    GameContextMenu14 = 77,
    GameContextMenu15 = 78,
    GameContextMenu16 = 79,
    GameContextMenu17 = 80,
    GameContextMenu18 = 81,
    GameContextMenu19 = 82,
    GameContextMenu20 = 83,
    GameContextMenu21 = 84,
    GameContextMenu22 = 85,
    GameContextMenu23 = 86,
    GameContextMenu24 = 87,
    DialogCloseAll = 88,
    DialogOptions = 89,
    DialogHelp = 90,
    DialogMilestones = 91,
    DialogNotes = 92,
    DialogMessages = 93,
    DialogMessagesChatFocus = 94,
    DialogInventory = 95,
    DialogCrafting = 96,
    DialogDismantle = 97,
    DialogEquipment = 98,
    DialogSkills = 99,
    DialogQuests = 100,
    DialogIslands = 101,
    MenuEnter = 102,
    MenuSubmit = 103,
    MenuNext = 104,
    MenuPrevious = 105,
    MenuUp = 106,
    MenuDown = 107,
    MenuLeft = 108,
    MenuRight = 109,
    MenuCancel = 110,
    MenuNextOption = 111,
    MenuPreviousOption = 112,
    MenuContextMenu = 113,
    MenuSelect = 114,
    DeveloperToggleDeveloperMode = 115,
    DeveloperToggleDeveloperTools = 116,
    DeveloperReloadGame = 117,
    DeveloperReloadAndContinueGame = 118,
    DeveloperReloadStylesheets = 119
}
export default Bindable;
export declare enum BindableType {
    Game = 0,
    GameItem = 1,
    GameQuickSlot = 2,
    GameContextMenu = 3,
    Dialog = 4,
    Menu = 5,
    Developer = 6,
    Mod = 7
}
