/*!
 * Copyright 2011-2025 Unlok
 * https://www.unlok.ca
 *
 * Credits & Thanks:
 * https://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
import type Human from "@wayward/game/game/entity/Human";
import { Milestone } from "@wayward/game/game/milestones/IMilestone";
import GameplayModifiersManager from "@wayward/game/game/options/modifiers/GameplayModifiersManager";
import type { MilestoneModifierGroup } from "@wayward/game/game/options/modifiers/milestone/IMilestoneModifier";
import MilestoneModifier from "@wayward/game/game/options/modifiers/milestone/MilestoneModifier";
import Abnormalizer from "@wayward/game/game/options/modifiers/milestone/modifiers/Abnormalizer";
import Afflicted from "@wayward/game/game/options/modifiers/milestone/modifiers/Afflicted";
import Apocryphal from "@wayward/game/game/options/modifiers/milestone/modifiers/Apocryphal";
import Artificer from "@wayward/game/game/options/modifiers/milestone/modifiers/Artificer";
import Benevolent from "@wayward/game/game/options/modifiers/milestone/modifiers/Benevolent";
import Boundless from "@wayward/game/game/options/modifiers/milestone/modifiers/Boundless";
import Challenger from "@wayward/game/game/options/modifiers/milestone/modifiers/Challenger";
import Chef from "@wayward/game/game/options/modifiers/milestone/modifiers/Chef";
import Collector from "@wayward/game/game/options/modifiers/milestone/modifiers/Collector";
import Contender from "@wayward/game/game/options/modifiers/milestone/modifiers/Contender";
import Crafter from "@wayward/game/game/options/modifiers/milestone/modifiers/Crafter";
import Curator from "@wayward/game/game/options/modifiers/milestone/modifiers/Curator";
import Cursebreaker from "@wayward/game/game/options/modifiers/milestone/modifiers/Cursebreaker";
import Cursed from "@wayward/game/game/options/modifiers/milestone/modifiers/Cursed";
import Dedicated from "@wayward/game/game/options/modifiers/milestone/modifiers/Dedicated";
import DestroyerOfMagi from "@wayward/game/game/options/modifiers/milestone/modifiers/DestroyerOfMagi";
import Diverse from "@wayward/game/game/options/modifiers/milestone/modifiers/Diverse";
import Doctor from "@wayward/game/game/options/modifiers/milestone/modifiers/Doctor";
import DragonSlayer from "@wayward/game/game/options/modifiers/milestone/modifiers/DragonSlayer";
import Explorer from "@wayward/game/game/options/modifiers/milestone/modifiers/Explorer";
import Exsanguinated from "@wayward/game/game/options/modifiers/milestone/modifiers/Exsanguinated";
import Exterminator from "@wayward/game/game/options/modifiers/milestone/modifiers/Exterminator";
import Friendly from "@wayward/game/game/options/modifiers/milestone/modifiers/Friendly";
import Gardener from "@wayward/game/game/options/modifiers/milestone/modifiers/Gardener";
import Gatherer from "@wayward/game/game/options/modifiers/milestone/modifiers/Gatherer";
import Grandmaster from "@wayward/game/game/options/modifiers/milestone/modifiers/Grandmaster";
import Helmsman from "@wayward/game/game/options/modifiers/milestone/modifiers/Helmsman";
import Hounded from "@wayward/game/game/options/modifiers/milestone/modifiers/Hounded";
import Hunter from "@wayward/game/game/options/modifiers/milestone/modifiers/Hunter";
import Huntsman from "@wayward/game/game/options/modifiers/milestone/modifiers/Huntsman";
import Invoker from "@wayward/game/game/options/modifiers/milestone/modifiers/Invoker";
import Locksmith from "@wayward/game/game/options/modifiers/milestone/modifiers/Locksmith";
import Malevolent from "@wayward/game/game/options/modifiers/milestone/modifiers/Malevolent";
import Masochist from "@wayward/game/game/options/modifiers/milestone/modifiers/Masochist";
import MasterOfAll from "@wayward/game/game/options/modifiers/milestone/modifiers/MasterOfAll";
import Merchant from "@wayward/game/game/options/modifiers/milestone/modifiers/Merchant";
import Multitasker from "@wayward/game/game/options/modifiers/milestone/modifiers/Multitasker";
import Murderer from "@wayward/game/game/options/modifiers/milestone/modifiers/Murderer";
import Navigator from "@wayward/game/game/options/modifiers/milestone/modifiers/Navigator";
import Notekeeper from "@wayward/game/game/options/modifiers/milestone/modifiers/Notekeeper";
import Oblivious from "@wayward/game/game/options/modifiers/milestone/modifiers/Oblivious";
import Operator from "@wayward/game/game/options/modifiers/milestone/modifiers/Operator";
import Pacifier from "@wayward/game/game/options/modifiers/milestone/modifiers/Pacifier";
import Prepared from "@wayward/game/game/options/modifiers/milestone/modifiers/Prepared";
import Pulchritudinous from "@wayward/game/game/options/modifiers/milestone/modifiers/Pulchritudinous";
import ReaperOfSouls from "@wayward/game/game/options/modifiers/milestone/modifiers/ReaperOfSouls";
import Retailer from "@wayward/game/game/options/modifiers/milestone/modifiers/Retailer";
import Rouseabout from "@wayward/game/game/options/modifiers/milestone/modifiers/Rouseabout";
import Runekeeper from "@wayward/game/game/options/modifiers/milestone/modifiers/RunekeeperModifier";
import Seafarer from "@wayward/game/game/options/modifiers/milestone/modifiers/Seafarer";
import Seasoned from "@wayward/game/game/options/modifiers/milestone/modifiers/Seasoned";
import Serene from "@wayward/game/game/options/modifiers/milestone/modifiers/Serene";
import Statistician from "@wayward/game/game/options/modifiers/milestone/modifiers/Statistician";
import Survivor from "@wayward/game/game/options/modifiers/milestone/modifiers/Survivor";
import Talented from "@wayward/game/game/options/modifiers/milestone/modifiers/Talented";
import Thaumaturgic from "@wayward/game/game/options/modifiers/milestone/modifiers/Thaumaturgic";
import Thrower from "@wayward/game/game/options/modifiers/milestone/modifiers/Thrower";
import Traitor from "@wayward/game/game/options/modifiers/milestone/modifiers/Traitor";
import Trapper from "@wayward/game/game/options/modifiers/milestone/modifiers/Trapper";
import TreasureHunter from "@wayward/game/game/options/modifiers/milestone/modifiers/TreasureHunter";
import Treasurer from "@wayward/game/game/options/modifiers/milestone/modifiers/Treasurer";
import Turbulent from "@wayward/game/game/options/modifiers/milestone/modifiers/Turbulent";
import Versatile from "@wayward/game/game/options/modifiers/milestone/modifiers/Versatile";
import Weathered from "@wayward/game/game/options/modifiers/milestone/modifiers/Weathered";
import Translation from "@wayward/game/language/Translation";
export declare const milestoneModifiers: {
    0: typeof Abnormalizer;
    67: typeof Afflicted;
    41: typeof Apocryphal;
    18: typeof Artificer;
    26: typeof Benevolent;
    27: typeof Boundless;
    37: typeof Challenger;
    1: typeof Chef;
    13: typeof Collector;
    36: typeof Contender;
    3: typeof Crafter;
    56: typeof Curator;
    71: typeof Cursebreaker;
    70: typeof Cursed;
    52: typeof Dedicated;
    38: typeof DestroyerOfMagi;
    42: typeof Diverse;
    17: typeof Doctor;
    21: typeof DragonSlayer;
    14: typeof Explorer;
    68: typeof Exsanguinated;
    2: typeof Exterminator;
    24: typeof Friendly;
    4: typeof Gardener;
    5: typeof Gatherer;
    15: typeof Grandmaster;
    39: typeof Helmsman;
    53: typeof Hounded;
    6: typeof Hunter;
    35: typeof Huntsman;
    62: typeof Invoker;
    7: typeof Locksmith;
    25: typeof Malevolent;
    49: typeof Masochist;
    45: typeof MasterOfAll;
    32: typeof Merchant;
    40: typeof Multitasker;
    47: typeof Murderer;
    20: typeof Navigator;
    33: typeof Notekeeper;
    72: typeof Oblivious;
    34: typeof Operator;
    31: typeof Pacifier;
    10: typeof Thrower;
    16: typeof Prepared;
    23: typeof Pulchritudinous;
    8: typeof ReaperOfSouls;
    48: typeof Retailer;
    19: typeof Seafarer;
    46: typeof Rouseabout;
    58: typeof Runekeeper;
    30: typeof Seasoned;
    54: typeof Serene;
    66: typeof Statistician;
    9: typeof Survivor;
    28: typeof Talented;
    57: typeof Thaumaturgic;
    44: typeof Traitor;
    11: typeof Trapper;
    12: typeof TreasureHunter;
    22: typeof Treasurer;
    65: typeof Turbulent;
    50: typeof Versatile;
    29: typeof Weathered;
};
declare class MilestoneModifiersManager extends GameplayModifiersManager<MilestoneModifier, Milestone, [Human?]> {
    constructor();
    translateModifierDescription(milestone: Milestone): Translation;
    has(milestone: Milestone): boolean;
    getUnlocked(): Milestone[];
    getAll(): Milestone[];
    isGlobal(milestone: Milestone): boolean;
    isNotGlobal(milestone: Milestone): boolean;
    getGroup(milestone: Milestone): MilestoneModifierGroup | undefined;
    sort(a: Milestone, b: Milestone): 0 | 1 | -1;
}
declare const _default: MilestoneModifiersManager;
export default _default;
