/*!
 * Copyright 2011-2024 Unlok
 * https://www.unlok.ca
 *
 * Credits & Thanks:
 * https://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
export declare enum SfxType {
    Boat = 0,
    Bow = 1,
    Chat = 2,
    Craft = 3,
    CreatureHit = 4,
    CreatureNoise = 5,
    Damaged = 6,
    DangerousMove = 7,
    Death = 8,
    Eating = 9,
    Encumbered = 10,
    Exceptional = 11,
    Extinguish = 12,
    Fail = 13,
    FluteNoteA = 14,
    FluteNoteB = 15,
    FluteNoteC = 16,
    FluteNoteD = 17,
    FluteNoteE = 18,
    FluteNoteF = 19,
    FluteNoteG = 20,
    FluteNoteH = 21,
    FluteNoteI = 22,
    GraniteHit = 23,
    Hit = 24,
    Hurt = 25,
    Minecart = 26,
    Miss = 27,
    Overburdened = 28,
    PickUp = 29,
    SandstoneHit = 30,
    Slip = 31,
    Swim = 32,
    Throw = 33,
    Trample = 34,
    TreeHit = 35,
    UiActivate = 36,
    UiChoose = 37,
    UiClose = 38,
    UiDisable = 39,
    UiEnable = 40,
    UiEquip = 41,
    UiInput = 42,
    UiInputdelete = 43,
    UiInvalid = 44,
    UiOpen = 45,
    UiOpensmall = 46,
    UiProtect = 47,
    UiReorder = 48,
    UiSelect = 49,
    UiSort = 50,
    UiStack = 51,
    UiTrade = 52,
    UiUnequip = 53,
    UiUnprotect = 54,
    UiUnstack = 55,
    Walk = 56,
    Water = 57,
    Wheelbarrow = 58,
    InvokeEvil = 59,
    InvokeChaos = 60,
    InvokeGood = 61,
    Sacrifice = 62
}
export type SfxUi = Extract<keyof typeof SfxType, `Ui${string}`> extends `Ui${infer RESULT}` ? Lowercase<RESULT> : never;
export declare enum Music {
    Shipwrecked = 0,
    OpeningTheme = 1,
    DarkerWorld = 2,
    Crux = 3,
    TheFirstSpark = 4,
    HauntingInterlude = 5,
    NomadsHeartBeat = 6,
    LootStep = 7,
    PerilsOfPlunder = 8,
    DreamInterlude = 9,
    TheWildBorn = 10,
    NightOwl = 11,
    SurvivalInstinct = 12,
    Savage = 13,
    Underworld = 14,
    ThirdSunrise = 15,
    WistfulInterlude = 16,
    ShudderSounds = 17
}
