/*!
 * Copyright 2011-2025 Unlok
 * https://www.unlok.ca
 *
 * Credits & Thanks:
 * https://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
export declare enum SfxType {
    Boat = 0,
    Bow = 1,
    Break = 2,
    Chat = 3,
    Craft = 4,
    CraftFail = 5,
    CreatureHit = 6,
    CreatureNoise = 7,
    Damaged = 8,
    DangerousMove = 9,
    Death = 10,
    Eating = 11,
    Encumbered = 12,
    Exceptional = 13,
    Extinguish = 14,
    Exude = 15,// Reversed GeneralMagicalAction sound
    Fail = 16,
    FluteNoteA = 17,
    FluteNoteB = 18,
    FluteNoteC = 19,
    FluteNoteD = 20,
    FluteNoteE = 21,
    FluteNoteF = 22,
    FluteNoteG = 23,
    FluteNoteH = 24,
    FluteNoteI = 25,
    GeneralAction = 26,
    GeneralMagicalAction = 27,
    GraniteHit = 28,
    Hit = 29,
    Hurt = 30,
    InvokeChaos = 31,
    InvokeEvil = 32,
    InvokeGood = 33,
    Minecart = 34,
    Miss = 35,
    Overburdened = 36,
    PickUp = 37,
    Sacrifice = 38,
    SandstoneHit = 39,
    Slip = 40,
    Swim = 41,
    Throw = 42,
    Trample = 43,
    TreeHit = 44,
    UiActivate = 45,
    UiChoose = 46,
    UiClose = 47,
    UiDisable = 48,
    UiEnable = 49,
    UiEquip = 50,
    UiInput = 51,
    UiInputdelete = 52,
    UiInvalid = 53,
    UiOpen = 54,
    UiOpensmall = 55,
    UiProtect = 56,
    UiReorder = 57,
    UiSelect = 58,
    UiSort = 59,
    UiStack = 60,
    UiTrade = 61,
    UiUnequip = 62,
    UiUnprotect = 63,
    UiUnstack = 64,
    Walk = 65,
    Water = 66,
    Wheelbarrow = 67,
    Curse = 68,
    CurseWarning = 69
}
export type SfxUi = Extract<keyof typeof SfxType, `Ui${string}`> extends `Ui${infer RESULT}` ? Lowercase<RESULT> : never;
export declare enum Music {
    Shipwrecked = 0,
    OpeningTheme = 1,
    DarkerWorld = 2,
    Crux = 3,
    TheFirstSpark = 4,
    HauntingInterlude = 5,
    NomadsHeartBeat = 6,
    LootStep = 7,
    PerilsOfPlunder = 8,
    DreamInterlude = 9,
    TheWildBorn = 10,
    NightOwl = 11,
    SurvivalInstinct = 12,
    Savage = 13,
    Underworld = 14,
    ThirdSunrise = 15,
    WistfulInterlude = 16,
    ShudderSounds = 17
}
