/*!
 * Copyright 2011-2025 Unlok
 * https://www.unlok.ca
 *
 * Credits & Thanks:
 * https://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
export declare enum SfxType {
    Boat = 0,
    Bow = 1,
    Break = 2,
    Chat = 3,
    Craft = 4,
    CraftFail = 5,
    CreatureHit = 6,
    CreatureNoise = 7,
    Curse = 8,
    CurseEventNewPlants = 9,
    CurseEventPlantDeath = 10,// Reversed CurseEventNewPlants sound
    CurseWarning = 11,
    Damaged = 12,
    DangerousMove = 13,
    Death = 14,
    Eating = 15,
    Encumbered = 16,
    Exceptional = 17,
    Extinguish = 18,
    Exude = 19,// Reversed GeneralMagicalAction sound
    Fail = 20,
    FluteNoteA = 21,
    FluteNoteB = 22,
    FluteNoteC = 23,
    FluteNoteD = 24,
    FluteNoteE = 25,
    FluteNoteF = 26,
    FluteNoteG = 27,
    FluteNoteH = 28,
    FluteNoteI = 29,
    GeneralAction = 30,
    GeneralMagicalAction = 31,
    GraniteHit = 32,
    Hit = 33,
    Hurt = 34,
    InvokeChaos = 35,
    InvokeEvil = 36,
    InvokeGood = 37,
    Minecart = 38,
    Miss = 39,
    Overburdened = 40,
    PickUp = 41,
    Sacrifice = 42,
    SandstoneHit = 43,
    Slip = 44,
    Swim = 45,
    Throw = 46,
    Trample = 47,
    TreeHit = 48,
    UiActivate = 49,
    UiChoose = 50,
    UiClose = 51,
    UiDisable = 52,
    UiEnable = 53,
    UiEquip = 54,
    UiInput = 55,
    UiInputdelete = 56,
    UiInvalid = 57,
    UiOpen = 58,
    UiOpensmall = 59,
    UiProtect = 60,
    UiReorder = 61,
    UiSelect = 62,
    UiSort = 63,
    UiStack = 64,
    UiTrade = 65,
    UiUnequip = 66,
    UiUnprotect = 67,
    UiUnstack = 68,
    Walk = 69,
    Water = 70,
    Wheelbarrow = 71
}
export type SfxUi = Extract<keyof typeof SfxType, `Ui${string}`> extends `Ui${infer RESULT}` ? Lowercase<RESULT> : never;
export declare enum Music {
    Shipwrecked = 0,
    OpeningTheme = 1,
    DarkerWorld = 2,
    Crux = 3,
    TheFirstSpark = 4,
    HauntingInterlude = 5,
    NomadsHeartBeat = 6,
    LootStep = 7,
    PerilsOfPlunder = 8,
    DreamInterlude = 9,
    TheWildBorn = 10,
    NightOwl = 11,
    SurvivalInstinct = 12,
    Savage = 13,
    Underworld = 14,
    ThirdSunrise = 15,
    WistfulInterlude = 16,
    ShudderSounds = 17
}
