/*!
 * Copyright Unlok, Vaughn Royko 2011-2020
 * http://www.unlok.ca
 *
 * Credits & Thanks:
 * http://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
import { ActionType, IActionDescription } from "entity/action/IAction";
declare const actionDescriptions: {
    52: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, import("../../item/Item").default]>;
    78: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    81: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    3: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.AttackType, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (import("../IEntity").AttackType | undefined)?]>;
    29: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    5: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default, void, [import("../../item/Item").default]>;
    16: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    74: IActionDescription<[import("entity/action/IAction").ActionArgument.Container, [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/IItem").IContainer, (boolean | undefined)?]>;
    51: IActionDescription<[], import("../player/Player").default | import("../npc/NPC").default, boolean, []>;
    27: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default, void, [import("../../item/Item").default]>;
    68: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemType, import("entity/action/IAction").ActionArgument.ItemArrayNearby, import("entity/action/IAction").ActionArgument.ItemArrayNearby, [import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/IItem").ItemType, import("../../item/Item").default[], import("../../item/Item").default[], (import("../../item/Item").default | undefined)?, (boolean | undefined)?]>;
    82: import("./Action").Action<[], import("../player/Player").default | import("../npc/NPC").default, void, []>;
    12: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?]>;
    0: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    41: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    40: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    33: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    63: import("./Action").Action<[], import("../player/Player").default | import("../npc/NPC").default, void, []>;
    8: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    57: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.String, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (boolean | undefined)?, (boolean | undefined)?, (string | undefined)?]>;
    7: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    86: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, [import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (import("../../item/Item").default | undefined)?]>;
    96: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory, [import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (import("../../item/Item").default | undefined)?]>;
    65: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.EquipType, [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default, void, [import("../../item/Item").default, import("../IHuman").EquipType, (boolean | undefined)?, (boolean | undefined)?]>;
    39: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    37: IActionDescription<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.AttackType, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (import("../IEntity").AttackType | undefined)?]>;
    23: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (boolean | undefined)?]>;
    72: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    14: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    89: IActionDescription<[[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Container, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.ItemType, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Quality, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.String, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (import("../../item/IItem").IContainer | undefined)?, (import("../../item/IItem").ItemType | undefined)?, (import("../../game/IObject").Quality | undefined)?, (string | undefined)?]>;
    53: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    71: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (boolean | undefined)?]>;
    11: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    47: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    79: IActionDescription<[], import("../player/Player").default | import("../npc/NPC").default, void, []>;
    62: import("./Action").Action<[], import("../player/Player").default, void, []>;
    28: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    94: import("./Action").Action<[import("entity/action/IAction").ActionArgument.Integer, [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Integer], [import("entity/action/IAction").ActionArgument.Object, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default, void, [number, number | boolean, any?]>;
    58: import("./Action").Action<[], import("../player/Player").default | import("../npc/NPC").default, void, []>;
    21: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default, void, [import("../../item/Item").default]>;
    17: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    88: IActionDescription<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.AttackType, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (import("../IEntity").AttackType | undefined)?]>;
    59: import("./Action").Action<[import("entity/action/IAction").ActionArgument.Direction], import("../player/Player").default, void, [import("../../utilities/math/Direction").Direction]>;
    67: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Container, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.ItemType, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Quality, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.String, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (import("../../item/IItem").IContainer | undefined)?, (import("../../item/IItem").ItemType | undefined)?, (import("../../game/IObject").Quality | undefined)?, (string | undefined)?]>;
    60: import("./Action").Action<[import("entity/action/IAction").ActionArgument.Vector2, [import("entity/action/IAction").ActionArgument.Direction, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default, void, [import("../../utilities/math/IVector").IVector2, (import("../../utilities/math/Direction").Direction | undefined)?]>;
    87: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default, void, [(import("../../item/Item").default | undefined)?]>;
    56: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default, void, [import("../../item/Item").default]>;
    32: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    30: IActionDescription<[import("entity/action/IAction").ActionArgument.Container, [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/IItem").IContainer, (boolean | undefined)?]>;
    50: IActionDescription<[], import("../player/Player").default | import("../npc/NPC").default, boolean, []>;
    13: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default, void, [import("../../item/Item").default]>;
    44: import("./Action").Action<[], import("../player/Player").default, void, []>;
    1: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?]>;
    55: import("./Action").Action<[], import("../player/Player").default | import("../npc/NPC").default, void, []>;
    84: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?]>;
    54: import("./Action").Action<[], import("../player/Player").default | import("../npc/NPC").default, void, []>;
    77: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    26: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    25: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    42: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    31: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, [import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (import("../../item/Item").default | undefined)?]>;
    91: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Boolean], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, boolean]>;
    73: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    20: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, [import("entity/action/IAction").ActionArgument.Undefined, import("entity/action/IAction").ActionArgument.Boolean]], import("../player/Player").default, void, [import("../../item/Item").default, (boolean | undefined)?]>;
    83: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, [import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (import("../../item/Item").default | undefined)?]>;
    22: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, [import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (import("../../item/Item").default | undefined)?]>;
    46: import("./Action").Action<[], import("../player/Player").default, void, []>;
    70: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Doodad, import("entity/action/IAction").ActionArgument.Creature], import("entity/action/IAction").ActionArgument.String], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../doodad/Doodad").default | import("../../item/Item").default | import("../creature/Creature").default, string]>;
    19: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, [import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Doodad, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (import("../../doodad/Doodad").default | import("../../item/Item").default | undefined)?]>;
    90: import("./Action").Action<[], import("../player/Player").default, void, []>;
    9: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Doodad, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.RestType, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default, void, [(import("../../item/Item").default | undefined)?, (import("../../doodad/Doodad").default | undefined)?, (import("../IHuman").RestType | undefined)?, (boolean | undefined)?]>;
    48: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    49: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    35: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default, void, [(import("../../item/Item").default | undefined)?, (boolean | undefined)?]>;
    6: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    15: IActionDescription<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.AttackType, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (import("../IEntity").AttackType | undefined)?]>;
    10: IActionDescription<[[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Doodad, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.RestType, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.Boolean, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default, void, [(import("../../item/Item").default | undefined)?, (import("../../doodad/Doodad").default | undefined)?, (import("../IHuman").RestType | undefined)?, (boolean | undefined)?]>;
    18: IActionDescription<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.AttackType, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (import("../IEntity").AttackType | undefined)?]>;
    75: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    43: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    4: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory, [import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (import("../../item/Item").default | undefined)?]>;
    24: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    45: import("./Action").Action<[], import("../player/Player").default, void, []>;
    38: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    34: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default]>;
    85: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default, void, [(import("../../item/Item").default | undefined)?]>;
    2: IActionDescription<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined], [import("entity/action/IAction").ActionArgument.AttackType, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?, (import("../IEntity").AttackType | undefined)?]>;
    69: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory]], import("../player/Player").default, void, [import("../../item/Item").default]>;
    76: import("./Action").Action<[import("entity/action/IAction").ActionArgument.NPCNearby], import("../player/Player").default | import("../npc/NPC").default, void, [import("../npc/NPC").default]>;
    36: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemInventory, [import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (import("../../item/Item").default | undefined)?]>;
    66: import("./Action").Action<[[import("entity/action/IAction").ActionArgument.ItemInventory, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [(import("../../item/Item").default | undefined)?]>;
    80: IActionDescription<[], import("../player/Player").default | import("../npc/NPC").default, void, []>;
    92: IActionDescription<[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Boolean], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, boolean]>;
    61: import("./Action").Action<[import("entity/action/IAction").ActionArgument.Direction, [import("entity/action/IAction").ActionArgument.Integer, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../utilities/math/Direction").Direction, (number | undefined)?]>;
    93: import("./Action").Action<[import("entity/action/IAction").ActionArgument.Container, [import("entity/action/IAction").ActionArgument.IntegerNumberArray, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default, void, [import("../../item/IItem").IContainer, (number[] | undefined)?]>;
    95: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, [import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.Undefined]], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, (import("../../item/Item").default | undefined)?]>;
    64: import("./Action").Action<[import("entity/action/IAction").ActionArgument.ItemNearby, import("entity/action/IAction").ActionArgument.ActionType], import("../player/Player").default | import("../npc/NPC").default, void, [import("../../item/Item").default, ActionType]>;
};
export default actionDescriptions;
