/*!
 * Copyright 2011-2025 Unlok
 * https://www.unlok.ca
 *
 * Credits & Thanks:
 * https://www.unlok.ca/credits-thanks/
 *
 * Wayward is a copyrighted and licensed work. Modification and/or distribution of any source files is prohibited. If you wish to modify the game in any way, please refer to the modding guide:
 * https://github.com/WaywardGame/types/wiki
 */
import { Quality } from "@wayward/game/game/IObject";
import Deity from "@wayward/game/game/deity/Deity";
import type Doodad from "@wayward/game/game/doodad/Doodad";
import { DamageType } from "@wayward/game/game/entity/IEntity";
import { EquipType } from "@wayward/game/game/entity/IHuman";
import { SkillType } from "@wayward/game/game/entity/skill/ISkills";
import { Stat } from "@wayward/game/game/entity/IStats";
import type { ActionId } from "@wayward/game/game/entity/action/usable/IUsableAction";
import type Creature from "@wayward/game/game/entity/creature/Creature";
import type Corpse from "@wayward/game/game/entity/creature/corpse/Corpse";
import type NPC from "@wayward/game/game/entity/npc/NPC";
import type Player from "@wayward/game/game/entity/player/Player";
import { StatusType } from "@wayward/game/game/entity/status/IStatus";
import type { IslandId } from "@wayward/game/game/island/IIsland";
import type Island from "@wayward/game/game/island/Island";
import { ItemType, ItemTypeExtra } from "@wayward/game/game/item/IItem";
import type Item from "@wayward/game/game/item/Item";
import type { MagicalPropertyIdentityHash } from "@wayward/game/game/magic/IMagicalProperty";
import { Milestone } from "@wayward/game/game/milestones/IMilestone";
import type TileEvent from "@wayward/game/game/tile/TileEvent";
import type Translation from "@wayward/game/language/Translation";
export interface IReferenceable {
    /**
     * Do not use this property directly, instead use `game.references.getReference()
     */
    referenceId?: number;
}
export declare enum ReferenceType {
    Item = 0,
    Creature = 1,
    Doodad = 2,
    NPC = 3,
    Player = 4,
    TileEvent = 5,
    Island = 6,
    Corpse = 7,
    Skill = 8,
    Milestone = 9,
    Recipe = 10,
    ItemType = 11,
    Dismantle = 12,
    Stat = 13,
    Action = 14,
    EquipSlot = 15,
    Deity = 16,
    Quality = 17,
    Magic = 18,
    Status = 19,
    Damage = 20,
    MagicCurse = 21
}
export declare const enumRefTypes: {
    8: typeof SkillType;
    9: typeof Milestone;
    10: typeof ItemType;
    11: {
        Bow: ItemType.Bow;
        None: ItemType.None;
        String: ItemType.String;
        HideGlue: ItemType.HideGlue;
        AnimalSkull: ItemType.AnimalSkull;
        GraniteArrow: ItemType.GraniteArrow;
        GraniteArrowhead: ItemType.GraniteArrowhead;
        PileOfAsh: ItemType.PileOfAsh;
        BarkLeggings: ItemType.BarkLeggings;
        BarkShield: ItemType.BarkShield;
        BarkTunic: ItemType.BarkTunic;
        Bone: ItemType.Bone;
        Branch: ItemType.Branch;
        CactusSpines: ItemType.CactusSpines;
        Charcoal: ItemType.Charcoal;
        GraniteFlooring: ItemType.GraniteFlooring;
        CookedMeat: ItemType.CookedMeat;
        Earthworm: ItemType.Earthworm;
        Feather: ItemType.Feather;
        Fertilizer: ItemType.Fertilizer;
        WaterskinOfSeawater: ItemType.WaterskinOfSeawater;
        FirePlough: ItemType.FirePlough;
        BeggartickSeeds: ItemType.BeggartickSeeds;
        Fossil: ItemType.Fossil;
        GoldCoins: ItemType.GoldCoins;
        GoldenChalice: ItemType.GoldenChalice;
        GoldenRing: ItemType.GoldenRing;
        GoldShortSword: ItemType.GoldShortSword;
        GrassSeeds: ItemType.GrassSeeds;
        IronOre: ItemType.IronOre;
        WoodenDowels: ItemType.WoodenDowels;
        Granite: ItemType.Granite;
        LeafBedroll: ItemType.LeafBedroll;
        Hide: ItemType.Hide;
        Leaves: ItemType.Leaves;
        Limestone: ItemType.Limestone;
        Log: ItemType.Log;
        GraniteMortarAndPestle: ItemType.GraniteMortarAndPestle;
        ButtonMushrooms: ItemType.ButtonMushrooms;
        Nopal: ItemType.Nopal;
        Peat: ItemType.Peat;
        Sandstone: ItemType.Sandstone;
        PileOfGravel: ItemType.PileOfGravel;
        PileOfBeachSand: ItemType.PileOfBeachSand;
        WoodenArrow: ItemType.WoodenArrow;
        GraniteAxe: ItemType.GraniteAxe;
        Bandage: ItemType.Bandage;
        WovenFabric: ItemType.WovenFabric;
        CactusNeedle: ItemType.CactusNeedle;
        GraniteShovel: ItemType.GraniteShovel;
        WoodenSpear: ItemType.WoodenSpear;
        Suture: ItemType.Suture;
        Raft: ItemType.Raft;
        RawMeat: ItemType.RawMeat;
        Raspberries: ItemType.Raspberries;
        FlyAmanita: ItemType.FlyAmanita;
        Rope: ItemType.Rope;
        MapleSeeds: ItemType.MapleSeeds;
        Badderlocks: ItemType.Badderlocks;
        SharpGlass: ItemType.SharpGlass;
        SharpGranite: ItemType.SharpGranite;
        Skullcap: ItemType.Skullcap;
        SmoothGranite: ItemType.SmoothGranite;
        Soil: ItemType.Soil;
        GraniteSpear: ItemType.GraniteSpear;
        Stones: ItemType.Stones;
        GraniteWall: ItemType.GraniteWall;
        StrippedBark: ItemType.StrippedBark;
        Leather: ItemType.Leather;
        Tannin: ItemType.Tannin;
        MilkThistleSeeds: ItemType.MilkThistleSeeds;
        TreeBark: ItemType.TreeBark;
        HoneyFungus: ItemType.HoneyFungus;
        ClematisVine: ItemType.ClematisVine;
        Twigs: ItemType.Twigs;
        Waterskin: ItemType.Waterskin;
        WoodenPole: ItemType.WoodenPole;
        PeatBandage: ItemType.PeatBandage;
        BowDrill: ItemType.BowDrill;
        FishingNet: ItemType.FishingNet;
        RawCod: ItemType.RawCod;
        CookedCod: ItemType.CookedCod;
        GraniteCampfire: ItemType.GraniteCampfire;
        VineWhip: ItemType.VineWhip;
        PileOfSnow: ItemType.PileOfSnow;
        BarkTorch: ItemType.BarkTorch;
        LitBarkTorch: ItemType.LitBarkTorch;
        HandDrill: ItemType.HandDrill;
        SmallBag: ItemType.SmallBag;
        Shale: ItemType.Shale;
        SharpenedBone: ItemType.SharpenedBone;
        Grindstone: ItemType.Grindstone;
        RawFishSteak: ItemType.RawFishSteak;
        CookedFishSteak: ItemType.CookedFishSteak;
        WaterskinOfDesalinatedWater: ItemType.WaterskinOfDesalinatedWater;
        BoatPaddle: ItemType.BoatPaddle;
        BullBoat: ItemType.BullBoat;
        RefinedSand: ItemType.RefinedSand;
        Spyglass: ItemType.Spyglass;
        Retort: ItemType.Retort;
        RawClay: ItemType.RawClay;
        RawClayBlowpipe: ItemType.RawClayBlowpipe;
        ClayBlowpipe: ItemType.ClayBlowpipe;
        LeatherBelt: ItemType.LeatherBelt;
        LeatherTunic: ItemType.LeatherTunic;
        LeatherBoots: ItemType.LeatherBoots;
        LeatherCap: ItemType.LeatherCap;
        LeatherGorget: ItemType.LeatherGorget;
        LeatherPants: ItemType.LeatherPants;
        LeatherGloves: ItemType.LeatherGloves;
        GraniteFurnace: ItemType.GraniteFurnace;
        SandstoneKiln: ItemType.SandstoneKiln;
        IronTongs: ItemType.IronTongs;
        Talc: ItemType.Talc;
        TalcumPowder: ItemType.TalcumPowder;
        WoodenSandCastFlask: ItemType.WoodenSandCastFlask;
        Lens: ItemType.Lens;
        PlantRoots: ItemType.PlantRoots;
        Lockpick: ItemType.Lockpick;
        BoneNeedle: ItemType.BoneNeedle;
        Pineapple: ItemType.Pineapple;
        TatteredMap: ItemType.TatteredMap;
        Coal: ItemType.Coal;
        SmeltedWroughtIron: ItemType.SmeltedWroughtIron;
        LimestonePowder: ItemType.LimestonePowder;
        SmeltedIron: ItemType.SmeltedIron;
        Backpack: ItemType.Backpack;
        RottenMeat: ItemType.RottenMeat;
        GraniteHammer: ItemType.GraniteHammer;
        RawChicken: ItemType.RawChicken;
        CookedChicken: ItemType.CookedChicken;
        GraniteAnvil: ItemType.GraniteAnvil;
        WoodenChest: ItemType.WoodenChest;
        IronShortSword: ItemType.IronShortSword;
        IronBreastplate: ItemType.IronBreastplate;
        IronBoots: ItemType.IronBoots;
        IronHelmet: ItemType.IronHelmet;
        IronGorget: ItemType.IronGorget;
        IronCuisses: ItemType.IronCuisses;
        IronGauntlets: ItemType.IronGauntlets;
        IronHeater: ItemType.IronHeater;
        SandstoneWall: ItemType.SandstoneWall;
        SandstoneFlooring: ItemType.SandstoneFlooring;
        SpiderSilk: ItemType.SpiderSilk;
        AnimalFat: ItemType.AnimalFat;
        TallowTorch: ItemType.TallowTorch;
        ClayFlakes: ItemType.ClayFlakes;
        GreenSand: ItemType.GreenSand;
        OldInstructionalScroll: ItemType.OldInstructionalScroll;
        SlimeBall: ItemType.SlimeBall;
        SlimeGlue: ItemType.SlimeGlue;
        CookedSpiderMeat: ItemType.CookedSpiderMeat;
        SpiderMeat: ItemType.SpiderMeat;
        IronLockpick: ItemType.IronLockpick;
        RottingVegetation: ItemType.RottingVegetation;
        Chives: ItemType.Chives;
        IronHammer: ItemType.IronHammer;
        IronSpear: ItemType.IronSpear;
        IronShovel: ItemType.IronShovel;
        IronDoubleAxe: ItemType.IronDoubleAxe;
        IronPickaxe: ItemType.IronPickaxe;
        Inkstick: ItemType.Inkstick;
        Coconut: ItemType.Coconut;
        PalmLeaf: ItemType.PalmLeaf;
        Offal: ItemType.Offal;
        BoneFragments: ItemType.BoneFragments;
        LitPoleTorch: ItemType.LitPoleTorch;
        CottonBoll: ItemType.CottonBoll;
        CottonSeeds: ItemType.CottonSeeds;
        CottonFabric: ItemType.CottonFabric;
        BonePole: ItemType.BonePole;
        Tourniquet: ItemType.Tourniquet;
        WroughtIronPickaxe: ItemType.WroughtIronPickaxe;
        WroughtIronDoubleAxe: ItemType.WroughtIronDoubleAxe;
        WroughtIronShovel: ItemType.WroughtIronShovel;
        WroughtIronSpear: ItemType.WroughtIronSpear;
        WroughtIronHammer: ItemType.WroughtIronHammer;
        WroughtIronLockpick: ItemType.WroughtIronLockpick;
        WroughtIronShield: ItemType.WroughtIronShield;
        WroughtIronGauntlets: ItemType.WroughtIronGauntlets;
        WroughtIronCuisses: ItemType.WroughtIronCuisses;
        WroughtIronGorget: ItemType.WroughtIronGorget;
        WroughtIronHelmet: ItemType.WroughtIronHelmet;
        WroughtIronBoots: ItemType.WroughtIronBoots;
        WroughtIronBreastplate: ItemType.WroughtIronBreastplate;
        WroughtIronShortSword: ItemType.WroughtIronShortSword;
        WoodenWall: ItemType.WoodenWall;
        WoodenFlooring: ItemType.WoodenFlooring;
        WoodenDoor: ItemType.WoodenDoor;
        FishingRod: ItemType.FishingRod;
        MessageInABottle: ItemType.MessageInABottle;
        CarbonPowder: ItemType.CarbonPowder;
        PileOfCompost: ItemType.PileOfCompost;
        FishGlue: ItemType.FishGlue;
        WoodenShavings: ItemType.WoodenShavings;
        GraniteDeadfall: ItemType.GraniteDeadfall;
        Snare: ItemType.Snare;
        WaterskinOfMedicinalWater: ItemType.WaterskinOfMedicinalWater;
        CharcoalBandage: ItemType.CharcoalBandage;
        WoodenTongs: ItemType.WoodenTongs;
        WroughtIronTongs: ItemType.WroughtIronTongs;
        SheetOfGlass: ItemType.SheetOfGlass;
        SolarStill: ItemType.SolarStill;
        TinWaterStill: ItemType.TinWaterStill;
        GraniteSundial: ItemType.GraniteSundial;
        LitTallowTorch: ItemType.LitTallowTorch;
        Sinew: ItemType.Sinew;
        ShortBow: ItemType.ShortBow;
        LongBow: ItemType.LongBow;
        CompositeBow: ItemType.CompositeBow;
        WaterskinOfPurifiedFreshWater: ItemType.WaterskinOfPurifiedFreshWater;
        WaterskinOfUnpurifiedFreshWater: ItemType.WaterskinOfUnpurifiedFreshWater;
        GlassBottle: ItemType.GlassBottle;
        Cork: ItemType.Cork;
        GlassBottleOfSeawater: ItemType.GlassBottleOfSeawater;
        GlassBottleOfDesalinatedWater: ItemType.GlassBottleOfDesalinatedWater;
        GlassBottleOfMedicinalWater: ItemType.GlassBottleOfMedicinalWater;
        GlassBottleOfPurifiedFreshWater: ItemType.GlassBottleOfPurifiedFreshWater;
        GlassBottleOfUnpurifiedFreshWater: ItemType.GlassBottleOfUnpurifiedFreshWater;
        WroughtIronArrow: ItemType.WroughtIronArrow;
        IronArrow: ItemType.IronArrow;
        GraniteBullet: ItemType.GraniteBullet;
        WroughtIronBullet: ItemType.WroughtIronBullet;
        IronBullet: ItemType.IronBullet;
        LeatherQuiver: ItemType.LeatherQuiver;
        Ectoplasm: ItemType.Ectoplasm;
        MagicalEssence: ItemType.MagicalEssence;
        WoodenFence: ItemType.WoodenFence;
        CreatureIdol: ItemType.CreatureIdol;
        CordedSling: ItemType.CordedSling;
        LeatherSling: ItemType.LeatherSling;
        WroughtIronArrowhead: ItemType.WroughtIronArrowhead;
        IronArrowhead: ItemType.IronArrowhead;
        Hammock: ItemType.Hammock;
        CottonBedroll: ItemType.CottonBedroll;
        FeatherBedroll: ItemType.FeatherBedroll;
        RawTaintedMeat: ItemType.RawTaintedMeat;
        CookedTaintedMeat: ItemType.CookedTaintedMeat;
        GraniteKnife: ItemType.GraniteKnife;
        RawBlindfish: ItemType.RawBlindfish;
        CookedBlindfish: ItemType.CookedBlindfish;
        Pemmican: ItemType.Pemmican;
        CookedPemmican: ItemType.CookedPemmican;
        Sail: ItemType.Sail;
        Sailboat: ItemType.Sailboat;
        ChickenEgg: ItemType.ChickenEgg;
        BoiledChickenEgg: ItemType.BoiledChickenEgg;
        SheafOfHay: ItemType.SheafOfHay;
        Niter: ItemType.Niter;
        Saltpeter: ItemType.Saltpeter;
        BlackPowder: ItemType.BlackPowder;
        FlintlockPistol: ItemType.FlintlockPistol;
        Giblets: ItemType.Giblets;
        ExplosiveTrap: ItemType.ExplosiveTrap;
        SkeletalMageWand: ItemType.SkeletalMageWand;
        RawClayJug: ItemType.RawClayJug;
        ClayJug: ItemType.ClayJug;
        ClayJugOfSeawater: ItemType.ClayJugOfSeawater;
        ClayJugOfDesalinatedWater: ItemType.ClayJugOfDesalinatedWater;
        ClayJugOfMedicinalWater: ItemType.ClayJugOfMedicinalWater;
        ClayJugOfPurifiedFreshWater: ItemType.ClayJugOfPurifiedFreshWater;
        ClayJugOfUnpurifiedFreshWater: ItemType.ClayJugOfUnpurifiedFreshWater;
        RawClayBrick: ItemType.RawClayBrick;
        ClayBrick: ItemType.ClayBrick;
        ClayWall: ItemType.ClayWall;
        ClayFlooring: ItemType.ClayFlooring;
        PineappleSeeds: ItemType.PineappleSeeds;
        RaspberrySeeds: ItemType.RaspberrySeeds;
        PricklyPearSeeds: ItemType.PricklyPearSeeds;
        ClematisSeeds: ItemType.ClematisSeeds;
        PaperSheet: ItemType.PaperSheet;
        PaperMold: ItemType.PaperMold;
        Beggarticks: ItemType.Beggarticks;
        MilkThistleFlowers: ItemType.MilkThistleFlowers;
        DrawnMap: ItemType.DrawnMap;
        TatteredClothShirt: ItemType.TatteredClothShirt;
        TatteredClothTrousers: ItemType.TatteredClothTrousers;
        WoodenGate: ItemType.WoodenGate;
        PoisonIvyLeaves: ItemType.PoisonIvyLeaves;
        PoisonIvySeeds: ItemType.PoisonIvySeeds;
        WroughtIronChest: ItemType.WroughtIronChest;
        IronChest: ItemType.IronChest;
        SwitchgrassSeeds: ItemType.SwitchgrassSeeds;
        Apple: ItemType.Apple;
        SpiderEggs: ItemType.SpiderEggs;
        TailFeathers: ItemType.TailFeathers;
        AppleSeeds: ItemType.AppleSeeds;
        VenomGland: ItemType.VenomGland;
        OrnateWoodenChest: ItemType.OrnateWoodenChest;
        RollOfRedCarpet: ItemType.RollOfRedCarpet;
        OrnateCape: ItemType.OrnateCape;
        FireBladder: ItemType.FireBladder;
        GoldenKey: ItemType.GoldenKey;
        WoodenShortSword: ItemType.WoodenShortSword;
        ClayKiln: ItemType.ClayKiln;
        ClayCampfire: ItemType.ClayCampfire;
        ClayFurnace: ItemType.ClayFurnace;
        CopperWaterStill: ItemType.CopperWaterStill;
        SandstoneCampfire: ItemType.SandstoneCampfire;
        SandstoneFurnace: ItemType.SandstoneFurnace;
        WroughtIronWaterStill: ItemType.WroughtIronWaterStill;
        GraniteKiln: ItemType.GraniteKiln;
        WroughtIronAnvil: ItemType.WroughtIronAnvil;
        IronAnvil: ItemType.IronAnvil;
        MageRobe: ItemType.MageRobe;
        CrackedOrb: ItemType.CrackedOrb;
        AnimalClaw: ItemType.AnimalClaw;
        AnimalPelt: ItemType.AnimalPelt;
        AnimalFur: ItemType.AnimalFur;
        Scales: ItemType.Scales;
        SharkFin: ItemType.SharkFin;
        RawReptileMeat: ItemType.RawReptileMeat;
        CookedReptileMeat: ItemType.CookedReptileMeat;
        Tentacles: ItemType.Tentacles;
        CookedTentacles: ItemType.CookedTentacles;
        WormMeat: ItemType.WormMeat;
        CookedWormMeat: ItemType.CookedWormMeat;
        GranitePickaxe: ItemType.GranitePickaxe;
        WroughtIronAxe: ItemType.WroughtIronAxe;
        IronAxe: ItemType.IronAxe;
        FertileSoil: ItemType.FertileSoil;
        GraniteHoe: ItemType.GraniteHoe;
        WroughtIronHoe: ItemType.WroughtIronHoe;
        IronHoe: ItemType.IronHoe;
        LavaBeetleHelmet: ItemType.LavaBeetleHelmet;
        SpruceCone: ItemType.SpruceCone;
        SpruceSeeds: ItemType.SpruceSeeds;
        SpruceNeedles: ItemType.SpruceNeedles;
        CypressCone: ItemType.CypressCone;
        CypressSeeds: ItemType.CypressSeeds;
        CypressLeaves: ItemType.CypressLeaves;
        Lettuce: ItemType.Lettuce;
        LettuceSeeds: ItemType.LettuceSeeds;
        ChiveSeeds: ItemType.ChiveSeeds;
        Potato: ItemType.Potato;
        PotatoSeeds: ItemType.PotatoSeeds;
        Carrot: ItemType.Carrot;
        CarrotSeeds: ItemType.CarrotSeeds;
        CornEar: ItemType.CornEar;
        CornSeeds: ItemType.CornSeeds;
        Cucumber: ItemType.Cucumber;
        CucumberSeeds: ItemType.CucumberSeeds;
        Tomato: ItemType.Tomato;
        TomatoSeeds: ItemType.TomatoSeeds;
        Pumpkin: ItemType.Pumpkin;
        PumpkinSeeds: ItemType.PumpkinSeeds;
        PricklyPearFruit: ItemType.PricklyPearFruit;
        SugarCaneStalks: ItemType.SugarCaneStalks;
        SugarCaneSeeds: ItemType.SugarCaneSeeds;
        BushelOfWheat: ItemType.BushelOfWheat;
        Wheat: ItemType.Wheat;
        CookedPotato: ItemType.CookedPotato;
        CookedCornCob: ItemType.CookedCornCob;
        BundleOfSwitchgrass: ItemType.BundleOfSwitchgrass;
        Cloak: ItemType.Cloak;
        WoodenMortarAndPestle: ItemType.WoodenMortarAndPestle;
        SandstoneMortarAndPestle: ItemType.SandstoneMortarAndPestle;
        WroughtIronMortarAndPestle: ItemType.WroughtIronMortarAndPestle;
        IronMortarAndPestle: ItemType.IronMortarAndPestle;
        RawClayMortarAndPestle: ItemType.RawClayMortarAndPestle;
        ClayMortarAndPestle: ItemType.ClayMortarAndPestle;
        CopperOre: ItemType.CopperOre;
        SmeltedCopper: ItemType.SmeltedCopper;
        CopperPickaxe: ItemType.CopperPickaxe;
        CopperDoubleAxe: ItemType.CopperDoubleAxe;
        CopperShovel: ItemType.CopperShovel;
        CopperSpear: ItemType.CopperSpear;
        CopperHammer: ItemType.CopperHammer;
        CopperLockpick: ItemType.CopperLockpick;
        CopperBuckler: ItemType.CopperBuckler;
        CopperGauntlets: ItemType.CopperGauntlets;
        CopperGreaves: ItemType.CopperGreaves;
        CopperGorget: ItemType.CopperGorget;
        CopperHelmet: ItemType.CopperHelmet;
        CopperBoots: ItemType.CopperBoots;
        CopperCuirass: ItemType.CopperCuirass;
        CopperShortSword: ItemType.CopperShortSword;
        CopperTongs: ItemType.CopperTongs;
        CopperArrow: ItemType.CopperArrow;
        CopperBullet: ItemType.CopperBullet;
        CopperArrowhead: ItemType.CopperArrowhead;
        CopperChest: ItemType.CopperChest;
        CopperAnvil: ItemType.CopperAnvil;
        CopperAxe: ItemType.CopperAxe;
        CopperHoe: ItemType.CopperHoe;
        CopperMortarAndPestle: ItemType.CopperMortarAndPestle;
        WaterskinOfGoatMilk: ItemType.WaterskinOfGoatMilk;
        ClayJugOfGoatMilk: ItemType.ClayJugOfGoatMilk;
        GlassBottleOfGoatMilk: ItemType.GlassBottleOfGoatMilk;
        Obsidian: ItemType.Obsidian;
        OrnateBlueBook: ItemType.OrnateBlueBook;
        Journal: ItemType.Journal;
        MossCoveredBook: ItemType.MossCoveredBook;
        GildedRedBook: ItemType.GildedRedBook;
        ArrowShaft: ItemType.ArrowShaft;
        SlitherSucker: ItemType.SlitherSucker;
        AberrantSlitherSucker: ItemType.AberrantSlitherSucker;
        StrawHat: ItemType.StrawHat;
        BlackplateSabatons: ItemType.BlackplateSabatons;
        BlackplateBreastplate: ItemType.BlackplateBreastplate;
        BlackplateGauntlets: ItemType.BlackplateGauntlets;
        BlackplateGorget: ItemType.BlackplateGorget;
        BlackplateGreaves: ItemType.BlackplateGreaves;
        BlackplateHelmet: ItemType.BlackplateHelmet;
        DeathKnightAxe: ItemType.DeathKnightAxe;
        Macuahuitl: ItemType.Macuahuitl;
        ObsidianArrow: ItemType.ObsidianArrow;
        ObsidianArrowhead: ItemType.ObsidianArrowhead;
        ObsidianAxe: ItemType.ObsidianAxe;
        ObsidianKnife: ItemType.ObsidianKnife;
        ObsidianShovel: ItemType.ObsidianShovel;
        ObsidianSpear: ItemType.ObsidianSpear;
        TumbleweedSeeds: ItemType.TumbleweedSeeds;
        CoconutHusk: ItemType.CoconutHusk;
        PeeledCoconut: ItemType.PeeledCoconut;
        CoconutMeat: ItemType.CoconutMeat;
        CoconutContainerOfCoconutWater: ItemType.CoconutContainerOfCoconutWater;
        CoconutContainer: ItemType.CoconutContainer;
        CoconutContainerOfSeawater: ItemType.CoconutContainerOfSeawater;
        CoconutContainerOfDesalinatedWater: ItemType.CoconutContainerOfDesalinatedWater;
        CoconutContainerOfMedicinalWater: ItemType.CoconutContainerOfMedicinalWater;
        CoconutContainerOfPurifiedFreshWater: ItemType.CoconutContainerOfPurifiedFreshWater;
        CoconutContainerOfUnpurifiedFreshWater: ItemType.CoconutContainerOfUnpurifiedFreshWater;
        CoconutContainerOfGoatMilk: ItemType.CoconutContainerOfGoatMilk;
        OldEducationalScroll: ItemType.OldEducationalScroll;
        StrippedHide: ItemType.StrippedHide;
        ClaySandCastFlask: ItemType.ClaySandCastFlask;
        SandstoneSandCastFlask: ItemType.SandstoneSandCastFlask;
        GraniteSandCastFlask: ItemType.GraniteSandCastFlask;
        BoneGlue: ItemType.BoneGlue;
        CutHide: ItemType.CutHide;
        BoneMeal: ItemType.BoneMeal;
        PileOfDesertSand: ItemType.PileOfDesertSand;
        JoshuaTreeLeaves: ItemType.JoshuaTreeLeaves;
        JoshuaTreeFruit: ItemType.JoshuaTreeFruit;
        JoshuaTreeSeeds: ItemType.JoshuaTreeSeeds;
        CookedJoshuaTreeFruit: ItemType.CookedJoshuaTreeFruit;
        JoshuaTreeFlowers: ItemType.JoshuaTreeFlowers;
        SaguaroCactusFruit: ItemType.SaguaroCactusFruit;
        SaguaroCactusSeeds: ItemType.SaguaroCactusSeeds;
        SaguaroCactusChunk: ItemType.SaguaroCactusChunk;
        GraniteWell: ItemType.GraniteWell;
        SandstoneWell: ItemType.SandstoneWell;
        ClayWell: ItemType.ClayWell;
        AloeVeraLeaves: ItemType.AloeVeraLeaves;
        AloeVeraSeeds: ItemType.AloeVeraSeeds;
        DeadScorpion: ItemType.DeadScorpion;
        DeadAberrantScorpion: ItemType.DeadAberrantScorpion;
        CookedScorpion: ItemType.CookedScorpion;
        CookedAberrantScorpion: ItemType.CookedAberrantScorpion;
        ScorpionStinger: ItemType.ScorpionStinger;
        CopperBakingTray: ItemType.CopperBakingTray;
        WroughtIronBakingTray: ItemType.WroughtIronBakingTray;
        IronBakingTray: ItemType.IronBakingTray;
        Flour: ItemType.Flour;
        Dough: ItemType.Dough;
        Hardtack: ItemType.Hardtack;
        HitchingPost: ItemType.HitchingPost;
        ShreddedPaper: ItemType.ShreddedPaper;
        RawMudskipper: ItemType.RawMudskipper;
        RawAberrantMudskipper: ItemType.RawAberrantMudskipper;
        CookedMudskipper: ItemType.CookedMudskipper;
        CookedAberrantMudskipper: ItemType.CookedAberrantMudskipper;
        RawRedSnapper: ItemType.RawRedSnapper;
        CookedRedSnapper: ItemType.CookedRedSnapper;
        RawWalleye: ItemType.RawWalleye;
        CookedWalleye: ItemType.CookedWalleye;
        WoodenShield: ItemType.WoodenShield;
        CopperRefinementTools: ItemType.CopperRefinementTools;
        WroughtIronRefinementTools: ItemType.WroughtIronRefinementTools;
        IronRefinementTools: ItemType.IronRefinementTools;
        ScaleBelt: ItemType.ScaleBelt;
        ScaleVest: ItemType.ScaleVest;
        ScaleBoots: ItemType.ScaleBoots;
        ScaleCap: ItemType.ScaleCap;
        ScaleBevor: ItemType.ScaleBevor;
        ScaleLeggings: ItemType.ScaleLeggings;
        ScaleGloves: ItemType.ScaleGloves;
        CookedJoshuaTreeFlowers: ItemType.CookedJoshuaTreeFlowers;
        SaguaroCactusRibs: ItemType.SaguaroCactusRibs;
        BladesOfGrass: ItemType.BladesOfGrass;
        AnimalDroppings: ItemType.AnimalDroppings;
        AnimalDung: ItemType.AnimalDung;
        Guano: ItemType.Guano;
        Tallow: ItemType.Tallow;
        TallowCandle: ItemType.TallowCandle;
        LitTallowCandle: ItemType.LitTallowCandle;
        WispDust: ItemType.WispDust;
        MagicalAspect: ItemType.MagicalAspect;
        GoldenSextant: ItemType.GoldenSextant;
        RawChoppedFish: ItemType.RawChoppedFish;
        CookedChoppedFish: ItemType.CookedChoppedFish;
        CookedFishKebab: ItemType.CookedFishKebab;
        AshCement: ItemType.AshCement;
        AshCementBrick: ItemType.AshCementBrick;
        AshCementFlooring: ItemType.AshCementFlooring;
        AshCementWall: ItemType.AshCementWall;
        IceShard: ItemType.IceShard;
        PenguinEgg: ItemType.PenguinEgg;
        BoiledPenguinEgg: ItemType.BoiledPenguinEgg;
        RawPenguinMeat: ItemType.RawPenguinMeat;
        CookedPenguinMeat: ItemType.CookedPenguinMeat;
        Crowberries: ItemType.Crowberries;
        CookedCrowberries: ItemType.CookedCrowberries;
        CrowberrySeeds: ItemType.CrowberrySeeds;
        Winterberries: ItemType.Winterberries;
        WinterberrySeeds: ItemType.WinterberrySeeds;
        ArcticPoppies: ItemType.ArcticPoppies;
        ArcticPoppySeeds: ItemType.ArcticPoppySeeds;
        PirateHat: ItemType.PirateHat;
        AloeVeraBandage: ItemType.AloeVeraBandage;
        SharkTooth: ItemType.SharkTooth;
        CopperKnife: ItemType.CopperKnife;
        WroughtIronKnife: ItemType.WroughtIronKnife;
        IronKnife: ItemType.IronKnife;
        TinOre: ItemType.TinOre;
        SmeltedTin: ItemType.SmeltedTin;
        TinPickaxe: ItemType.TinPickaxe;
        TinDoubleAxe: ItemType.TinDoubleAxe;
        TinShovel: ItemType.TinShovel;
        TinSpear: ItemType.TinSpear;
        TinHammer: ItemType.TinHammer;
        TinLockpick: ItemType.TinLockpick;
        TinShield: ItemType.TinShield;
        TinGloves: ItemType.TinGloves;
        TinChausses: ItemType.TinChausses;
        TinBevor: ItemType.TinBevor;
        TinHelmet: ItemType.TinHelmet;
        TinFootgear: ItemType.TinFootgear;
        TinCuirass: ItemType.TinCuirass;
        TinShortSword: ItemType.TinShortSword;
        TinTongs: ItemType.TinTongs;
        TinArrow: ItemType.TinArrow;
        TinBullet: ItemType.TinBullet;
        TinArrowhead: ItemType.TinArrowhead;
        TinChest: ItemType.TinChest;
        TinAnvil: ItemType.TinAnvil;
        TinAxe: ItemType.TinAxe;
        TinHoe: ItemType.TinHoe;
        TinMortarAndPestle: ItemType.TinMortarAndPestle;
        TinBakingTray: ItemType.TinBakingTray;
        TinRefinementTools: ItemType.TinRefinementTools;
        TinKnife: ItemType.TinKnife;
        SmeltedBronze: ItemType.SmeltedBronze;
        BronzePickaxe: ItemType.BronzePickaxe;
        BronzeDoubleAxe: ItemType.BronzeDoubleAxe;
        BronzeShovel: ItemType.BronzeShovel;
        BronzeSpear: ItemType.BronzeSpear;
        BronzeHammer: ItemType.BronzeHammer;
        BronzeLockpick: ItemType.BronzeLockpick;
        BronzeKiteShield: ItemType.BronzeKiteShield;
        BronzeGauntlets: ItemType.BronzeGauntlets;
        BronzeGreaves: ItemType.BronzeGreaves;
        BronzeBevor: ItemType.BronzeBevor;
        BronzeHelmet: ItemType.BronzeHelmet;
        BronzeBoots: ItemType.BronzeBoots;
        BronzeChestArmor: ItemType.BronzeChestArmor;
        BronzeShortSword: ItemType.BronzeShortSword;
        BronzeTongs: ItemType.BronzeTongs;
        BronzeArrow: ItemType.BronzeArrow;
        BronzeBullet: ItemType.BronzeBullet;
        BronzeArrowhead: ItemType.BronzeArrowhead;
        BronzeChest: ItemType.BronzeChest;
        BronzeAnvil: ItemType.BronzeAnvil;
        BronzeAxe: ItemType.BronzeAxe;
        BronzeHoe: ItemType.BronzeHoe;
        BronzeMortarAndPestle: ItemType.BronzeMortarAndPestle;
        BronzeBakingTray: ItemType.BronzeBakingTray;
        BronzeRefinementTools: ItemType.BronzeRefinementTools;
        BronzeKnife: ItemType.BronzeKnife;
        IceBrick: ItemType.IceBrick;
        SnowBrick: ItemType.SnowBrick;
        IceWall: ItemType.IceWall;
        IceFlooring: ItemType.IceFlooring;
        SnowWall: ItemType.SnowWall;
        SnowFlooring: ItemType.SnowFlooring;
        CaliginousScrap: ItemType.CaliginousScrap;
        MagicalExtract: ItemType.MagicalExtract;
        ShimmeringFibers: ItemType.ShimmeringFibers;
        MagicalTwine: ItemType.MagicalTwine;
        SandstoneHammer: ItemType.SandstoneHammer;
        SandstoneBullet: ItemType.SandstoneBullet;
        SandstoneAnvil: ItemType.SandstoneAnvil;
        SnowScarecrow: ItemType.SnowScarecrow;
        FrozenFlesh: ItemType.FrozenFlesh;
        AnimalTusk: ItemType.AnimalTusk;
        WhitePineCone: ItemType.WhitePineCone;
        WhitePineSeeds: ItemType.WhitePineSeeds;
        WhitePineNeedles: ItemType.WhitePineNeedles;
        FurCoat: ItemType.FurCoat;
        FurMittens: ItemType.FurMittens;
        FurBoots: ItemType.FurBoots;
        BirdDroppings: ItemType.BirdDroppings;
        HardenedCoil: ItemType.HardenedCoil;
        MagicalBinding: ItemType.MagicalBinding;
        ArmoredScales: ItemType.ArmoredScales;
        RawPangolinMeat: ItemType.RawPangolinMeat;
        CookedPangolinMeat: ItemType.CookedPangolinMeat;
        ArmoredScaleBelt: ItemType.ArmoredScaleBelt;
        ArmoredScaleVest: ItemType.ArmoredScaleVest;
        ArmoredScaleBoots: ItemType.ArmoredScaleBoots;
        ArmoredScaleCrown: ItemType.ArmoredScaleCrown;
        ArmoredScaleBevor: ItemType.ArmoredScaleBevor;
        ArmoredScaleCuisses: ItemType.ArmoredScaleCuisses;
        ArmoredScaleGloves: ItemType.ArmoredScaleGloves;
        TinNeedle: ItemType.TinNeedle;
        CopperNeedle: ItemType.CopperNeedle;
        WroughtIronNeedle: ItemType.WroughtIronNeedle;
        IronNeedle: ItemType.IronNeedle;
        BronzeNeedle: ItemType.BronzeNeedle;
        TuftsOfTanglehead: ItemType.TuftsOfTanglehead;
        TangleheadSeeds: ItemType.TangleheadSeeds;
        WispInAGlassBottle: ItemType.WispInAGlassBottle;
        AberrantWispInAGlassBottle: ItemType.AberrantWispInAGlassBottle;
        WispInAClayJug: ItemType.WispInAClayJug;
        AberrantWispInAClayJug: ItemType.AberrantWispInAClayJug;
        WispInACoconutContainer: ItemType.WispInACoconutContainer;
        AberrantWispInACoconutContainer: ItemType.AberrantWispInACoconutContainer;
        WispInAWaterskin: ItemType.WispInAWaterskin;
        AberrantWispInAWaterskin: ItemType.AberrantWispInAWaterskin;
        StrawScarecrow: ItemType.StrawScarecrow;
        CactusScarecrow: ItemType.CactusScarecrow;
        ClothShirt: ItemType.ClothShirt;
        ClothTrousers: ItemType.ClothTrousers;
        UnripePapaya: ItemType.UnripePapaya;
        Papaya: ItemType.Papaya;
        PapayaSeeds: ItemType.PapayaSeeds;
        PalapalaiFrond: ItemType.PalapalaiFrond;
        PalapalaiSpores: ItemType.PalapalaiSpores;
        ButtonMushroomSpores: ItemType.ButtonMushroomSpores;
        FlyAmanitaSpores: ItemType.FlyAmanitaSpores;
        BrambleCrown: ItemType.BrambleCrown;
        DarkBrambleCrown: ItemType.DarkBrambleCrown;
        Cotton: ItemType.Cotton;
        WaterskinOfSwampWater: ItemType.WaterskinOfSwampWater;
        GlassBottleOfSwampWater: ItemType.GlassBottleOfSwampWater;
        ClayJugOfSwampWater: ItemType.ClayJugOfSwampWater;
        CoconutContainerOfSwampWater: ItemType.CoconutContainerOfSwampWater;
        WaterskinOfFilteredWater: ItemType.WaterskinOfFilteredWater;
        GlassBottleOfFilteredWater: ItemType.GlassBottleOfFilteredWater;
        ClayJugOfFilteredWater: ItemType.ClayJugOfFilteredWater;
        CoconutContainerOfFilteredWater: ItemType.CoconutContainerOfFilteredWater;
        ClayFilter: ItemType.ClayFilter;
        SandstoneAxe: ItemType.SandstoneAxe;
        SandstoneShovel: ItemType.SandstoneShovel;
        SharpSandstone: ItemType.SharpSandstone;
        SmoothSandstone: ItemType.SmoothSandstone;
        SandstoneSpear: ItemType.SandstoneSpear;
        SandstoneKnife: ItemType.SandstoneKnife;
        SandstonePickaxe: ItemType.SandstonePickaxe;
        SandstoneHoe: ItemType.SandstoneHoe;
        SandstoneDeadfall: ItemType.SandstoneDeadfall;
        SandstoneSundial: ItemType.SandstoneSundial;
        WoodenPlank: ItemType.WoodenPlank;
        WoodenWheel: ItemType.WoodenWheel;
        WoodenAxle: ItemType.WoodenAxle;
        WoodenMinecart: ItemType.WoodenMinecart;
        WoodenRail: ItemType.WoodenRail;
        WoodenTrack: ItemType.WoodenTrack;
        TinWheel: ItemType.TinWheel;
        TinAxle: ItemType.TinAxle;
        TinMinecart: ItemType.TinMinecart;
        TinRail: ItemType.TinRail;
        TinTrack: ItemType.TinTrack;
        CopperWheel: ItemType.CopperWheel;
        CopperAxle: ItemType.CopperAxle;
        CopperMinecart: ItemType.CopperMinecart;
        CopperRail: ItemType.CopperRail;
        CopperTrack: ItemType.CopperTrack;
        WroughtIronWheel: ItemType.WroughtIronWheel;
        WroughtIronAxle: ItemType.WroughtIronAxle;
        WroughtIronMinecart: ItemType.WroughtIronMinecart;
        WroughtIronRail: ItemType.WroughtIronRail;
        WroughtIronTrack: ItemType.WroughtIronTrack;
        IronWheel: ItemType.IronWheel;
        IronAxle: ItemType.IronAxle;
        IronMinecart: ItemType.IronMinecart;
        IronRail: ItemType.IronRail;
        IronTrack: ItemType.IronTrack;
        BronzeWheel: ItemType.BronzeWheel;
        BronzeAxle: ItemType.BronzeAxle;
        BronzeMinecart: ItemType.BronzeMinecart;
        BronzeRail: ItemType.BronzeRail;
        BronzeTrack: ItemType.BronzeTrack;
        BasaltArrow: ItemType.BasaltArrow;
        BasaltArrowhead: ItemType.BasaltArrowhead;
        Basalt: ItemType.Basalt;
        BasaltMortarAndPestle: ItemType.BasaltMortarAndPestle;
        BasaltAxe: ItemType.BasaltAxe;
        BasaltShovel: ItemType.BasaltShovel;
        SharpBasalt: ItemType.SharpBasalt;
        SmoothBasalt: ItemType.SmoothBasalt;
        BasaltSpear: ItemType.BasaltSpear;
        BasaltFlooring: ItemType.BasaltFlooring;
        BasaltWall: ItemType.BasaltWall;
        BasaltCampfire: ItemType.BasaltCampfire;
        BasaltFurnace: ItemType.BasaltFurnace;
        BasaltHammer: ItemType.BasaltHammer;
        BasaltAnvil: ItemType.BasaltAnvil;
        BasaltDeadfall: ItemType.BasaltDeadfall;
        IronWaterStill: ItemType.IronWaterStill;
        BasaltSundial: ItemType.BasaltSundial;
        BasaltBullet: ItemType.BasaltBullet;
        BasaltKnife: ItemType.BasaltKnife;
        BasaltKiln: ItemType.BasaltKiln;
        BasaltPickaxe: ItemType.BasaltPickaxe;
        BasaltHoe: ItemType.BasaltHoe;
        BasaltSandCastFlask: ItemType.BasaltSandCastFlask;
        BasaltWell: ItemType.BasaltWell;
        WoodenTrackGate: ItemType.WoodenTrackGate;
        MoldyScroll: ItemType.MoldyScroll;
        MysteriousParchment: ItemType.MysteriousParchment;
        MagicalInscription: ItemType.MagicalInscription;
        CattailLeaves: ItemType.CattailLeaves;
        CattailShoots: ItemType.CattailShoots;
        CattailFlowers: ItemType.CattailFlowers;
        CattailSeeds: ItemType.CattailSeeds;
        CobblestoneFlooring: ItemType.CobblestoneFlooring;
        WaterLilies: ItemType.WaterLilies;
        Mud: ItemType.Mud;
        SpikerushSheaths: ItemType.SpikerushSheaths;
        SpikerushSeeds: ItemType.SpikerushSeeds;
        WoodenBookcase: ItemType.WoodenBookcase;
        GraniteLighthouse: ItemType.GraniteLighthouse;
        SandstoneLighthouse: ItemType.SandstoneLighthouse;
        ClayLighthouse: ItemType.ClayLighthouse;
        BasaltLighthouse: ItemType.BasaltLighthouse;
        WoodenCage: ItemType.WoodenCage;
        FullWoodenCage: ItemType.FullWoodenCage;
        TinCage: ItemType.TinCage;
        FullTinCage: ItemType.FullTinCage;
        CopperCage: ItemType.CopperCage;
        FullCopperCage: ItemType.FullCopperCage;
        WroughtIronCage: ItemType.WroughtIronCage;
        FullWroughtIronCage: ItemType.FullWroughtIronCage;
        IronCage: ItemType.IronCage;
        FullIronCage: ItemType.FullIronCage;
        BronzeCage: ItemType.BronzeCage;
        FullBronzeCage: ItemType.FullBronzeCage;
        Amber: ItemType.Amber;
        Tourmaline: ItemType.Tourmaline;
        Topaz: ItemType.Topaz;
        Opal: ItemType.Opal;
        Sapphire: ItemType.Sapphire;
        WoodGolemFigure: ItemType.WoodGolemFigure;
        ClayGolemFigure: ItemType.ClayGolemFigure;
        GraniteGolemFigure: ItemType.GraniteGolemFigure;
        SandstoneGolemFigure: ItemType.SandstoneGolemFigure;
        BasaltGolemFigure: ItemType.BasaltGolemFigure;
        AberrantWoodGolemFigure: ItemType.AberrantWoodGolemFigure;
        AberrantClayGolemFigure: ItemType.AberrantClayGolemFigure;
        AberrantGraniteGolemFigure: ItemType.AberrantGraniteGolemFigure;
        AberrantSandstoneGolemFigure: ItemType.AberrantSandstoneGolemFigure;
        AberrantBasaltGolemFigure: ItemType.AberrantBasaltGolemFigure;
        GraniteDripstone: ItemType.GraniteDripstone;
        SandstoneDripstone: ItemType.SandstoneDripstone;
        BasaltDripstone: ItemType.BasaltDripstone;
        ClayDripstone: ItemType.ClayDripstone;
        BronzeWaterStill: ItemType.BronzeWaterStill;
        ArmorStand: ItemType.ArmorStand;
        RuneOfEvil: ItemType.RuneOfEvil;
        RuneOfChaos: ItemType.RuneOfChaos;
        RuneOfGood: ItemType.RuneOfGood;
        GraniteAltar: ItemType.GraniteAltar;
        WoodenWheelbarrow: ItemType.WoodenWheelbarrow;
        TinWheelbarrow: ItemType.TinWheelbarrow;
        CopperWheelbarrow: ItemType.CopperWheelbarrow;
        WroughtIronWheelbarrow: ItemType.WroughtIronWheelbarrow;
        IronWheelbarrow: ItemType.IronWheelbarrow;
        BronzeWheelbarrow: ItemType.BronzeWheelbarrow;
        GraniteCrucible: ItemType.GraniteCrucible;
        SandstoneCrucible: ItemType.SandstoneCrucible;
        BasaltCrucible: ItemType.BasaltCrucible;
        RawClayCrucible: ItemType.RawClayCrucible;
        ClayCrucible: ItemType.ClayCrucible;
        SandstoneAltar: ItemType.SandstoneAltar;
        BasaltAltar: ItemType.BasaltAltar;
        ClayAltar: ItemType.ClayAltar;
        PineResin: ItemType.PineResin;
        SpruceResin: ItemType.SpruceResin;
        CypressResin: ItemType.CypressResin;
        Pitch: ItemType.Pitch;
        PitchGlue: ItemType.PitchGlue;
        MagicalOrb: ItemType.MagicalOrb;
        RawAberrantCod: ItemType.RawAberrantCod;
        CookedAberrantCod: ItemType.CookedAberrantCod;
        RawAberrantBlindfish: ItemType.RawAberrantBlindfish;
        CookedAberrantBlindfish: ItemType.CookedAberrantBlindfish;
        RawAberrantRedSnapper: ItemType.RawAberrantRedSnapper;
        CookedAberrantRedSnapper: ItemType.CookedAberrantRedSnapper;
        RawAberrantWalleye: ItemType.RawAberrantWalleye;
        CookedAberrantWalleye: ItemType.CookedAberrantWalleye;
        FishBones: ItemType.FishBones;
        AnimalCartilage: ItemType.AnimalCartilage;
        GelatinPowder: ItemType.GelatinPowder;
        Gelatin: ItemType.Gelatin;
        Aspic: ItemType.Aspic;
        FruitCocktail: ItemType.FruitCocktail;
        VegetableTerrine: ItemType.VegetableTerrine;
        TatteredClothBandana: ItemType.TatteredClothBandana;
        ClothBandana: ItemType.ClothBandana;
        RustedScimitar: ItemType.RustedScimitar;
        TricorneHat: ItemType.TricorneHat;
        SandstoneArrowhead: ItemType.SandstoneArrowhead;
        SandstoneArrow: ItemType.SandstoneArrow;
        ReedFlute: ItemType.ReedFlute;
        WoodenFlute: ItemType.WoodenFlute;
        RawClayFlute: ItemType.RawClayFlute;
        ClayFlute: ItemType.ClayFlute;
        BoneFlute: ItemType.BoneFlute;
        TinFlute: ItemType.TinFlute;
        CopperFlute: ItemType.CopperFlute;
        WroughtIronFlute: ItemType.WroughtIronFlute;
        IronFlute: ItemType.IronFlute;
        BronzeFlute: ItemType.BronzeFlute;
        StrippedLeather: ItemType.StrippedLeather;
        ChickenEggshells: ItemType.ChickenEggshells;
        PenguinEggshells: ItemType.PenguinEggshells;
        MagicalMote: ItemType.MagicalMote;
        UnrefinedSugar: ItemType.UnrefinedSugar;
        RefinedSugar: ItemType.RefinedSugar;
        CandiedFruit: ItemType.CandiedFruit;
        CandiedSugar: ItemType.CandiedSugar;
        RawClayBakingTray: ItemType.RawClayBakingTray;
        ClayBakingTray: ItemType.ClayBakingTray;
        GlassBakingTray: ItemType.GlassBakingTray;
        RawClayPan: ItemType.RawClayPan;
        ClayPan: ItemType.ClayPan;
        GlassPan: ItemType.GlassPan;
        TinPan: ItemType.TinPan;
        CopperPan: ItemType.CopperPan;
        WroughtIronPan: ItemType.WroughtIronPan;
        IronPan: ItemType.IronPan;
        BronzePan: ItemType.BronzePan;
        PumpkinPie: ItemType.PumpkinPie;
        FruitPie: ItemType.FruitPie;
        JackOLantern: ItemType.JackOLantern;
        DriedLeaves: ItemType.DriedLeaves;
        Last: ItemType.Last;
        TatteredMap_RolledUp: ItemTypeExtra.TatteredMap_RolledUp;
        TatteredMap_Completed: ItemTypeExtra.TatteredMap_Completed;
        WoodenBookcase_25: ItemTypeExtra.WoodenBookcase_25;
        WoodenBookcase_50: ItemTypeExtra.WoodenBookcase_50;
        WoodenBookcase_75: ItemTypeExtra.WoodenBookcase_75;
        WoodenBookcase_100: ItemTypeExtra.WoodenBookcase_100;
        RuneOfEvilSplinters: ItemTypeExtra.RuneOfEvilSplinters;
        RuneOfGoodCharred: ItemTypeExtra.RuneOfGoodCharred;
        TallySticks: ItemTypeExtra.TallySticks;
        JackOLantern2: ItemTypeExtra.JackOLantern2;
        JackOLantern3: ItemTypeExtra.JackOLantern3;
        StrawScarecrow2: ItemTypeExtra.StrawScarecrow2;
        StrawScarecrow3: ItemTypeExtra.StrawScarecrow3;
        CactusScarecrow2: ItemTypeExtra.CactusScarecrow2;
        CactusScarecrow3: ItemTypeExtra.CactusScarecrow3;
        SnowScarecrow2: ItemTypeExtra.SnowScarecrow2;
        SnowScarecrow3: ItemTypeExtra.SnowScarecrow3;
        RuneOfEvil_Cursed: ItemTypeExtra.RuneOfEvil_Cursed;
        RuneOfGood_Cursed: ItemTypeExtra.RuneOfGood_Cursed;
        RuneOfChaos_Cursed: ItemTypeExtra.RuneOfChaos_Cursed;
    };
    12: typeof ItemType;
    13: typeof Stat;
    19: typeof StatusType;
    14: boolean;
    15: typeof EquipType;
    16: typeof Deity;
    17: typeof Quality;
    18: boolean;
    21: boolean;
    20: typeof DamageType;
};
export type EnumReferenceTypes = keyof typeof enumRefTypes;
export type EntityReferenceTypes = ReferenceType.Corpse | ReferenceType.Creature | ReferenceType.Doodad | ReferenceType.Item | ReferenceType.NPC | ReferenceType.Player | ReferenceType.TileEvent;
export declare const enumRefColorRegistry: PartialRecord<EnumReferenceTypes, (entry: string | number) => Translation>;
export declare const enumRefTranslatorRegistry: PartialRecord<EnumReferenceTypes, (entry: string | number) => Translation>;
export declare function registerEnumRefTranslator<ENUM extends number = number>(type: EnumReferenceTypes, translator: (entry: string | ENUM) => Translation): (entry: string | ENUM) => Translation;
export declare function registerEnumRefColor<ENUM extends number = number>(type: EnumReferenceTypes, supplier: (entry: string | ENUM) => Translation): (entry: string | ENUM) => Translation;
export type ReferenceableReferenceTypes = Exclude<ReferenceType, EnumReferenceTypes>;
export declare const referenceableRefTypes: Set<ReferenceableReferenceTypes>;
export interface IReferenceTypeMap {
    [ReferenceType.Item]: Item;
    [ReferenceType.Creature]: Creature;
    [ReferenceType.Doodad]: Doodad;
    [ReferenceType.NPC]: NPC;
    [ReferenceType.Player]: Player;
    [ReferenceType.TileEvent]: TileEvent;
    [ReferenceType.Island]: Island;
    [ReferenceType.Corpse]: Corpse;
    [ReferenceType.Skill]: [ReferenceType.Skill, SkillType];
    [ReferenceType.Milestone]: [ReferenceType.Milestone, Milestone];
    [ReferenceType.Recipe]: [ReferenceType.Recipe, ItemType];
    [ReferenceType.ItemType]: [ReferenceType.ItemType, ItemType | ItemTypeExtra];
    [ReferenceType.Dismantle]: [ReferenceType.Dismantle, ItemType];
    [ReferenceType.Stat]: [ReferenceType.Stat, Stat];
    [ReferenceType.Action]: [ReferenceType.Action, ActionId];
    [ReferenceType.EquipSlot]: [ReferenceType.EquipSlot, EquipType];
    [ReferenceType.Deity]: [ReferenceType.Deity, Deity];
    [ReferenceType.Quality]: [ReferenceType.Quality, Quality];
    [ReferenceType.Magic]: [ReferenceType.Magic, MagicalPropertyIdentityHash];
    [ReferenceType.MagicCurse]: [ReferenceType.MagicCurse, MagicalPropertyIdentityHash];
    [ReferenceType.Status]: [ReferenceType.Status, StatusType];
    [ReferenceType.Damage]: [ReferenceType.Damage, DamageType];
}
export type ReferenceContext = [number, ReferenceType?];
type ReferenceId<REFTYPE extends ReferenceType> = IReferenceTypeMap[REFTYPE] extends [REFTYPE, infer IdType, any?] ? IdType : number;
export type Reference<REFTYPE extends ReferenceType | undefined = ReferenceType | undefined> = REFTYPE extends ReferenceType ? [id: ReferenceId<REFTYPE>, type: REFTYPE, context?: ReferenceContext, islandId?: IslandId, objectId?: number] : [number];
export type Referenceable = IReferenceTypeMap[ReferenceableReferenceTypes];
export type ResolveReference<REFTYPE extends ReferenceType> = IReferenceTypeMap[REFTYPE];
export type EnumReferenceResolved<REFTYPE extends EnumReferenceTypes = EnumReferenceTypes> = IReferenceTypeMap[REFTYPE];
export declare namespace Reference {
    function create(id: number): Reference;
    function create<REFTYPE extends ReferenceType>(id: ReferenceId<REFTYPE>, type: REFTYPE): Reference;
    function equals(a?: Reference, b?: Reference): boolean;
}
export {};
