on:
  push:
    branches:
      - main
      - master
      - development

env:
  REPO_NAME: ${{ github.event.repository.name }}
  EXTRA_ARGS: ${{ github.ref == 'refs/heads/development' && '--tag dev' || '' }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Parse package.json
        id: set_var
        run: |
          content=`cat ./package.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"
          typesversion=$(echo ${{fromJson(steps.set_var.outputs.packageJson).version}} | cut -c 2-999)
          echo "$typesversion"
          echo "TYPES_VERSION=$typesversion" >> $GITHUB_ENV
      - name: zip
        run: |
          cd ../
          zip -r $REPO_NAME.zip $REPO_NAME -x "$REPO_NAME/.git/*" "$REPO_NAME/.github/*" "$REPO_NAME/node_modules/*"

      - name: Delete release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
        run: |
          gh release delete "v$TYPES_VERSION" --cleanup-tag --yes

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "v$TYPES_VERSION" \
              --repo="$GITHUB_REPOSITORY" \
              --target="${{ github.sha }}" \
              --title="v$TYPES_VERSION" \
              --generate-notes \
              $EXTRA_ARGS \
              "../$REPO_NAME.zip#$REPO_NAME.zip"

      - run: npm publish --provenance --access public $EXTRA_ARGS
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
